// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ManagePluginRequest within kubernetes types, where deepcopy-gen is used.
func (in *ManagePluginRequest) DeepCopyInto(out *ManagePluginRequest) {
	p := proto.Clone(in).(*ManagePluginRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagePluginRequest. Required by controller-gen.
func (in *ManagePluginRequest) DeepCopy() *ManagePluginRequest {
	if in == nil {
		return nil
	}
	out := new(ManagePluginRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ManagePluginRequest. Required by controller-gen.
func (in *ManagePluginRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
