// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: management/plugin/plugin.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginManagement_ManagePlugin_FullMethodName = "/vink.kubevm.io.apis.management.plugin.v1alpha1.PluginManagement/ManagePlugin"
)

// PluginManagementClient is the client API for PluginManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginManagementClient interface {
	ManagePlugin(ctx context.Context, in *ManagePluginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type pluginManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginManagementClient(cc grpc.ClientConnInterface) PluginManagementClient {
	return &pluginManagementClient{cc}
}

func (c *pluginManagementClient) ManagePlugin(ctx context.Context, in *ManagePluginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PluginManagement_ManagePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginManagementServer is the server API for PluginManagement service.
// All implementations must embed UnimplementedPluginManagementServer
// for forward compatibility.
type PluginManagementServer interface {
	ManagePlugin(context.Context, *ManagePluginRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPluginManagementServer()
}

// UnimplementedPluginManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginManagementServer struct{}

func (UnimplementedPluginManagementServer) ManagePlugin(context.Context, *ManagePluginRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManagePlugin not implemented")
}
func (UnimplementedPluginManagementServer) mustEmbedUnimplementedPluginManagementServer() {}
func (UnimplementedPluginManagementServer) testEmbeddedByValue()                          {}

// UnsafePluginManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginManagementServer will
// result in compilation errors.
type UnsafePluginManagementServer interface {
	mustEmbedUnimplementedPluginManagementServer()
}

func RegisterPluginManagementServer(s grpc.ServiceRegistrar, srv PluginManagementServer) {
	// If the following call pancis, it indicates UnimplementedPluginManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginManagement_ServiceDesc, srv)
}

func _PluginManagement_ManagePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginManagementServer).ManagePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginManagement_ManagePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginManagementServer).ManagePlugin(ctx, req.(*ManagePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginManagement_ServiceDesc is the grpc.ServiceDesc for PluginManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vink.kubevm.io.apis.management.plugin.v1alpha1.PluginManagement",
	HandlerType: (*PluginManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ManagePlugin",
			Handler:    _PluginManagement_ManagePlugin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management/plugin/plugin.proto",
}
