// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: management/plugin/plugin.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plugin int32

const (
	Plugin_MULTUS      Plugin = 0
	Plugin_KUBE_OVN    Plugin = 1
	Plugin_ROOK_CEPH   Plugin = 2
	Plugin_SNAPSHOTTER Plugin = 3
	Plugin_MONITOR     Plugin = 4
	Plugin_KUBEVIRT    Plugin = 5
	Plugin_CDI         Plugin = 6
)

// Enum value maps for Plugin.
var (
	Plugin_name = map[int32]string{
		0: "MULTUS",
		1: "KUBE_OVN",
		2: "ROOK_CEPH",
		3: "SNAPSHOTTER",
		4: "MONITOR",
		5: "KUBEVIRT",
		6: "CDI",
	}
	Plugin_value = map[string]int32{
		"MULTUS":      0,
		"KUBE_OVN":    1,
		"ROOK_CEPH":   2,
		"SNAPSHOTTER": 3,
		"MONITOR":     4,
		"KUBEVIRT":    5,
		"CDI":         6,
	}
)

func (x Plugin) Enum() *Plugin {
	p := new(Plugin)
	*p = x
	return p
}

func (x Plugin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Plugin) Descriptor() protoreflect.EnumDescriptor {
	return file_management_plugin_plugin_proto_enumTypes[0].Descriptor()
}

func (Plugin) Type() protoreflect.EnumType {
	return &file_management_plugin_plugin_proto_enumTypes[0]
}

func (x Plugin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Plugin.Descriptor instead.
func (Plugin) EnumDescriptor() ([]byte, []int) {
	return file_management_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

type Action int32

const (
	Action_INSTALL   Action = 0
	Action_UNINSTALL Action = 1
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "INSTALL",
		1: "UNINSTALL",
	}
	Action_value = map[string]int32{
		"INSTALL":   0,
		"UNINSTALL": 1,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_management_plugin_plugin_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_management_plugin_plugin_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_management_plugin_plugin_proto_rawDescGZIP(), []int{1}
}

type ManagePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        Plugin                 `protobuf:"varint,1,opt,name=plugin,proto3,enum=vink.kubevm.io.apis.management.plugin.v1alpha1.Plugin" json:"plugin,omitempty"`
	Action        Action                 `protobuf:"varint,2,opt,name=action,proto3,enum=vink.kubevm.io.apis.management.plugin.v1alpha1.Action" json:"action,omitempty"`
	Values        string                 `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagePluginRequest) Reset() {
	*x = ManagePluginRequest{}
	mi := &file_management_plugin_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagePluginRequest) ProtoMessage() {}

func (x *ManagePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_plugin_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagePluginRequest.ProtoReflect.Descriptor instead.
func (*ManagePluginRequest) Descriptor() ([]byte, []int) {
	return file_management_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ManagePluginRequest) GetPlugin() Plugin {
	if x != nil {
		return x.Plugin
	}
	return Plugin_MULTUS
}

func (x *ManagePluginRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_INSTALL
}

func (x *ManagePluginRequest) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

var File_management_plugin_plugin_proto protoreflect.FileDescriptor

const file_management_plugin_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1emanagement/plugin/plugin.proto\x12.vink.kubevm.io.apis.management.plugin.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x01\n" +
	"\x13ManagePluginRequest\x12N\n" +
	"\x06plugin\x18\x01 \x01(\x0e26.vink.kubevm.io.apis.management.plugin.v1alpha1.PluginR\x06plugin\x12N\n" +
	"\x06action\x18\x02 \x01(\x0e26.vink.kubevm.io.apis.management.plugin.v1alpha1.ActionR\x06action\x12\x16\n" +
	"\x06values\x18\x03 \x01(\tR\x06values*f\n" +
	"\x06Plugin\x12\n" +
	"\n" +
	"\x06MULTUS\x10\x00\x12\f\n" +
	"\bKUBE_OVN\x10\x01\x12\r\n" +
	"\tROOK_CEPH\x10\x02\x12\x0f\n" +
	"\vSNAPSHOTTER\x10\x03\x12\v\n" +
	"\aMONITOR\x10\x04\x12\f\n" +
	"\bKUBEVIRT\x10\x05\x12\a\n" +
	"\x03CDI\x10\x06*$\n" +
	"\x06Action\x12\v\n" +
	"\aINSTALL\x10\x00\x12\r\n" +
	"\tUNINSTALL\x10\x012\x7f\n" +
	"\x10PluginManagement\x12k\n" +
	"\fManagePlugin\x12C.vink.kubevm.io.apis.management.plugin.v1alpha1.ManagePluginRequest\x1a\x16.google.protobuf.EmptyB;Z9github.com/kubevm.io/vink/apis/management/plugin/v1alpha1b\x06proto3"

var (
	file_management_plugin_plugin_proto_rawDescOnce sync.Once
	file_management_plugin_plugin_proto_rawDescData []byte
)

func file_management_plugin_plugin_proto_rawDescGZIP() []byte {
	file_management_plugin_plugin_proto_rawDescOnce.Do(func() {
		file_management_plugin_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_plugin_plugin_proto_rawDesc), len(file_management_plugin_plugin_proto_rawDesc)))
	})
	return file_management_plugin_plugin_proto_rawDescData
}

var file_management_plugin_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_management_plugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_management_plugin_plugin_proto_goTypes = []any{
	(Plugin)(0),                 // 0: vink.kubevm.io.apis.management.plugin.v1alpha1.Plugin
	(Action)(0),                 // 1: vink.kubevm.io.apis.management.plugin.v1alpha1.Action
	(*ManagePluginRequest)(nil), // 2: vink.kubevm.io.apis.management.plugin.v1alpha1.ManagePluginRequest
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_management_plugin_plugin_proto_depIdxs = []int32{
	0, // 0: vink.kubevm.io.apis.management.plugin.v1alpha1.ManagePluginRequest.plugin:type_name -> vink.kubevm.io.apis.management.plugin.v1alpha1.Plugin
	1, // 1: vink.kubevm.io.apis.management.plugin.v1alpha1.ManagePluginRequest.action:type_name -> vink.kubevm.io.apis.management.plugin.v1alpha1.Action
	2, // 2: vink.kubevm.io.apis.management.plugin.v1alpha1.PluginManagement.ManagePlugin:input_type -> vink.kubevm.io.apis.management.plugin.v1alpha1.ManagePluginRequest
	3, // 3: vink.kubevm.io.apis.management.plugin.v1alpha1.PluginManagement.ManagePlugin:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_management_plugin_plugin_proto_init() }
func file_management_plugin_plugin_proto_init() {
	if File_management_plugin_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_plugin_plugin_proto_rawDesc), len(file_management_plugin_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_plugin_plugin_proto_goTypes,
		DependencyIndexes: file_management_plugin_plugin_proto_depIdxs,
		EnumInfos:         file_management_plugin_plugin_proto_enumTypes,
		MessageInfos:      file_management_plugin_plugin_proto_msgTypes,
	}.Build()
	File_management_plugin_plugin_proto = out.File
	file_management_plugin_plugin_proto_goTypes = nil
	file_management_plugin_plugin_proto_depIdxs = nil
}
