/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubevm.io/vink/pkg/k8s/apis/vink/v1alpha1"
	scheme "github.com/kubevm.io/vink/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VinksGetter has a method to return a VinkInterface.
// A group's client should implement this interface.
type VinksGetter interface {
	Vinks(namespace string) VinkInterface
}

// VinkInterface has methods to work with Vink resources.
type VinkInterface interface {
	Create(ctx context.Context, vink *v1alpha1.Vink, opts v1.CreateOptions) (*v1alpha1.Vink, error)
	Update(ctx context.Context, vink *v1alpha1.Vink, opts v1.UpdateOptions) (*v1alpha1.Vink, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vink *v1alpha1.Vink, opts v1.UpdateOptions) (*v1alpha1.Vink, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Vink, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VinkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Vink, err error)
	VinkExpansion
}

// vinks implements VinkInterface
type vinks struct {
	*gentype.ClientWithList[*v1alpha1.Vink, *v1alpha1.VinkList]
}

// newVinks returns a Vinks
func newVinks(c *VinkV1alpha1Client, namespace string) *vinks {
	return &vinks{
		gentype.NewClientWithList[*v1alpha1.Vink, *v1alpha1.VinkList](
			"vinks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.Vink { return &v1alpha1.Vink{} },
			func() *v1alpha1.VinkList { return &v1alpha1.VinkList{} }),
	}
}
