/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubevm.io/vink/pkg/k8s/apis/vink/v1alpha1"
	scheme "github.com/kubevm.io/vink/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VirtualMachineClaimsGetter has a method to return a VirtualMachineClaimInterface.
// A group's client should implement this interface.
type VirtualMachineClaimsGetter interface {
	VirtualMachineClaims(namespace string) VirtualMachineClaimInterface
}

// VirtualMachineClaimInterface has methods to work with VirtualMachineClaim resources.
type VirtualMachineClaimInterface interface {
	Create(ctx context.Context, virtualMachineClaim *v1alpha1.VirtualMachineClaim, opts v1.CreateOptions) (*v1alpha1.VirtualMachineClaim, error)
	Update(ctx context.Context, virtualMachineClaim *v1alpha1.VirtualMachineClaim, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineClaim, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualMachineClaim *v1alpha1.VirtualMachineClaim, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VirtualMachineClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VirtualMachineClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineClaim, err error)
	VirtualMachineClaimExpansion
}

// virtualMachineClaims implements VirtualMachineClaimInterface
type virtualMachineClaims struct {
	*gentype.ClientWithList[*v1alpha1.VirtualMachineClaim, *v1alpha1.VirtualMachineClaimList]
}

// newVirtualMachineClaims returns a VirtualMachineClaims
func newVirtualMachineClaims(c *VinkV1alpha1Client, namespace string) *virtualMachineClaims {
	return &virtualMachineClaims{
		gentype.NewClientWithList[*v1alpha1.VirtualMachineClaim, *v1alpha1.VirtualMachineClaimList](
			"virtualmachineclaims",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.VirtualMachineClaim { return &v1alpha1.VirtualMachineClaim{} },
			func() *v1alpha1.VirtualMachineClaimList { return &v1alpha1.VirtualMachineClaimList{} }),
	}
}
