// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using WatchResponse within kubernetes types, where deepcopy-gen is used.
func (in *WatchResponse) DeepCopyInto(out *WatchResponse) {
	p := proto.Clone(in).(*WatchResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchResponse. Required by controller-gen.
func (in *WatchResponse) DeepCopy() *WatchResponse {
	if in == nil {
		return nil
	}
	out := new(WatchResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new WatchResponse. Required by controller-gen.
func (in *WatchResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
