// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: management/template/v1alpha1/template.proto

package v1alpha1

import (
	context "context"
	types "github.com/kubevm.io/vink/apis/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemplateManagement_Get_FullMethodName    = "/vink.kubevm.io.apis.management.template.v1alpha1.TemplateManagement/Get"
	TemplateManagement_List_FullMethodName   = "/vink.kubevm.io.apis.management.template.v1alpha1.TemplateManagement/List"
	TemplateManagement_Create_FullMethodName = "/vink.kubevm.io.apis.management.template.v1alpha1.TemplateManagement/Create"
	TemplateManagement_Update_FullMethodName = "/vink.kubevm.io.apis.management.template.v1alpha1.TemplateManagement/Update"
	TemplateManagement_Delete_FullMethodName = "/vink.kubevm.io.apis.management.template.v1alpha1.TemplateManagement/Delete"
	TemplateManagement_Watch_FullMethodName  = "/vink.kubevm.io.apis.management.template.v1alpha1.TemplateManagement/Watch"
)

// TemplateManagementClient is the client API for TemplateManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateManagementClient interface {
	Get(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*types.Template, error)
	List(ctx context.Context, in *types.ListRequest, opts ...grpc.CallOption) (*types.TemplateList, error)
	Create(ctx context.Context, in *types.Template, opts ...grpc.CallOption) (*types.Template, error)
	Update(ctx context.Context, in *types.Template, opts ...grpc.CallOption) (*types.Template, error)
	Delete(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Watch(ctx context.Context, in *types.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type templateManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateManagementClient(cc grpc.ClientConnInterface) TemplateManagementClient {
	return &templateManagementClient{cc}
}

func (c *templateManagementClient) Get(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*types.Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Template)
	err := c.cc.Invoke(ctx, TemplateManagement_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateManagementClient) List(ctx context.Context, in *types.ListRequest, opts ...grpc.CallOption) (*types.TemplateList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.TemplateList)
	err := c.cc.Invoke(ctx, TemplateManagement_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateManagementClient) Create(ctx context.Context, in *types.Template, opts ...grpc.CallOption) (*types.Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Template)
	err := c.cc.Invoke(ctx, TemplateManagement_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateManagementClient) Update(ctx context.Context, in *types.Template, opts ...grpc.CallOption) (*types.Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Template)
	err := c.cc.Invoke(ctx, TemplateManagement_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateManagementClient) Delete(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TemplateManagement_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateManagementClient) Watch(ctx context.Context, in *types.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TemplateManagement_ServiceDesc.Streams[0], TemplateManagement_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[types.WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TemplateManagement_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// TemplateManagementServer is the server API for TemplateManagement service.
// All implementations must embed UnimplementedTemplateManagementServer
// for forward compatibility.
type TemplateManagementServer interface {
	Get(context.Context, *types.NamespaceName) (*types.Template, error)
	List(context.Context, *types.ListRequest) (*types.TemplateList, error)
	Create(context.Context, *types.Template) (*types.Template, error)
	Update(context.Context, *types.Template) (*types.Template, error)
	Delete(context.Context, *types.NamespaceName) (*emptypb.Empty, error)
	Watch(*types.WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedTemplateManagementServer()
}

// UnimplementedTemplateManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplateManagementServer struct{}

func (UnimplementedTemplateManagementServer) Get(context.Context, *types.NamespaceName) (*types.Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTemplateManagementServer) List(context.Context, *types.ListRequest) (*types.TemplateList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTemplateManagementServer) Create(context.Context, *types.Template) (*types.Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTemplateManagementServer) Update(context.Context, *types.Template) (*types.Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTemplateManagementServer) Delete(context.Context, *types.NamespaceName) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTemplateManagementServer) Watch(*types.WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedTemplateManagementServer) mustEmbedUnimplementedTemplateManagementServer() {}
func (UnimplementedTemplateManagementServer) testEmbeddedByValue()                            {}

// UnsafeTemplateManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateManagementServer will
// result in compilation errors.
type UnsafeTemplateManagementServer interface {
	mustEmbedUnimplementedTemplateManagementServer()
}

func RegisterTemplateManagementServer(s grpc.ServiceRegistrar, srv TemplateManagementServer) {
	// If the following call pancis, it indicates UnimplementedTemplateManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemplateManagement_ServiceDesc, srv)
}

func _TemplateManagement_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.NamespaceName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateManagementServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateManagement_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateManagementServer).Get(ctx, req.(*types.NamespaceName))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateManagement_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateManagementServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateManagement_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateManagementServer).List(ctx, req.(*types.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateManagement_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateManagementServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateManagement_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateManagementServer).Create(ctx, req.(*types.Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateManagement_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateManagementServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateManagement_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateManagementServer).Update(ctx, req.(*types.Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateManagement_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.NamespaceName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateManagementServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateManagement_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateManagementServer).Delete(ctx, req.(*types.NamespaceName))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateManagement_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(types.WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TemplateManagementServer).Watch(m, &grpc.GenericServerStream[types.WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TemplateManagement_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// TemplateManagement_ServiceDesc is the grpc.ServiceDesc for TemplateManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vink.kubevm.io.apis.management.template.v1alpha1.TemplateManagement",
	HandlerType: (*TemplateManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TemplateManagement_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TemplateManagement_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TemplateManagement_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TemplateManagement_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TemplateManagement_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _TemplateManagement_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "management/template/v1alpha1/template.proto",
}
