// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: management/subnet/v1alpha1/subnet.proto

package v1alpha1

import (
	types "github.com/kubevm.io/vink/apis/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         []*types.Subnet        `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	Modified      []*types.Subnet        `protobuf:"bytes,2,rep,name=modified,proto3" json:"modified,omitempty"`
	Deleted       []*types.Subnet        `protobuf:"bytes,3,rep,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_management_subnet_v1alpha1_subnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_subnet_v1alpha1_subnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_management_subnet_v1alpha1_subnet_proto_rawDescGZIP(), []int{0}
}

func (x *WatchResponse) GetAdded() []*types.Subnet {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *WatchResponse) GetModified() []*types.Subnet {
	if x != nil {
		return x.Modified
	}
	return nil
}

func (x *WatchResponse) GetDeleted() []*types.Subnet {
	if x != nil {
		return x.Deleted
	}
	return nil
}

var File_management_subnet_v1alpha1_subnet_proto protoreflect.FileDescriptor

const file_management_subnet_v1alpha1_subnet_proto_rawDesc = "" +
	"\n" +
	"'management/subnet/v1alpha1/subnet.proto\x12.vink.kubevm.io.apis.management.subnet.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11types/types.proto\x1a\x12types/subnet.proto\"\xc4\x01\n" +
	"\rWatchResponse\x127\n" +
	"\x05added\x18\x01 \x03(\v2!.vink.kubevm.io.apis.types.SubnetR\x05added\x12=\n" +
	"\bmodified\x18\x02 \x03(\v2!.vink.kubevm.io.apis.types.SubnetR\bmodified\x12;\n" +
	"\adeleted\x18\x03 \x03(\v2!.vink.kubevm.io.apis.types.SubnetR\adeleted2\x9c\x04\n" +
	"\x10SubnetManagement\x12R\n" +
	"\x03Get\x12(.vink.kubevm.io.apis.types.NamespaceName\x1a!.vink.kubevm.io.apis.types.Subnet\x12U\n" +
	"\x04List\x12&.vink.kubevm.io.apis.types.ListRequest\x1a%.vink.kubevm.io.apis.types.SubnetList\x12N\n" +
	"\x06Create\x12!.vink.kubevm.io.apis.types.Subnet\x1a!.vink.kubevm.io.apis.types.Subnet\x12N\n" +
	"\x06Update\x12!.vink.kubevm.io.apis.types.Subnet\x1a!.vink.kubevm.io.apis.types.Subnet\x12J\n" +
	"\x06Delete\x12(.vink.kubevm.io.apis.types.NamespaceName\x1a\x16.google.protobuf.Empty\x12q\n" +
	"\x05Watch\x12'.vink.kubevm.io.apis.types.WatchRequest\x1a=.vink.kubevm.io.apis.management.subnet.v1alpha1.WatchResponse0\x01B;Z9github.com/kubevm.io/vink/apis/management/subnet/v1alpha1b\x06proto3"

var (
	file_management_subnet_v1alpha1_subnet_proto_rawDescOnce sync.Once
	file_management_subnet_v1alpha1_subnet_proto_rawDescData []byte
)

func file_management_subnet_v1alpha1_subnet_proto_rawDescGZIP() []byte {
	file_management_subnet_v1alpha1_subnet_proto_rawDescOnce.Do(func() {
		file_management_subnet_v1alpha1_subnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_subnet_v1alpha1_subnet_proto_rawDesc), len(file_management_subnet_v1alpha1_subnet_proto_rawDesc)))
	})
	return file_management_subnet_v1alpha1_subnet_proto_rawDescData
}

var file_management_subnet_v1alpha1_subnet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_management_subnet_v1alpha1_subnet_proto_goTypes = []any{
	(*WatchResponse)(nil),       // 0: vink.kubevm.io.apis.management.subnet.v1alpha1.WatchResponse
	(*types.Subnet)(nil),        // 1: vink.kubevm.io.apis.types.Subnet
	(*types.NamespaceName)(nil), // 2: vink.kubevm.io.apis.types.NamespaceName
	(*types.ListRequest)(nil),   // 3: vink.kubevm.io.apis.types.ListRequest
	(*types.WatchRequest)(nil),  // 4: vink.kubevm.io.apis.types.WatchRequest
	(*types.SubnetList)(nil),    // 5: vink.kubevm.io.apis.types.SubnetList
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_management_subnet_v1alpha1_subnet_proto_depIdxs = []int32{
	1, // 0: vink.kubevm.io.apis.management.subnet.v1alpha1.WatchResponse.added:type_name -> vink.kubevm.io.apis.types.Subnet
	1, // 1: vink.kubevm.io.apis.management.subnet.v1alpha1.WatchResponse.modified:type_name -> vink.kubevm.io.apis.types.Subnet
	1, // 2: vink.kubevm.io.apis.management.subnet.v1alpha1.WatchResponse.deleted:type_name -> vink.kubevm.io.apis.types.Subnet
	2, // 3: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Get:input_type -> vink.kubevm.io.apis.types.NamespaceName
	3, // 4: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.List:input_type -> vink.kubevm.io.apis.types.ListRequest
	1, // 5: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Create:input_type -> vink.kubevm.io.apis.types.Subnet
	1, // 6: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Update:input_type -> vink.kubevm.io.apis.types.Subnet
	2, // 7: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Delete:input_type -> vink.kubevm.io.apis.types.NamespaceName
	4, // 8: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Watch:input_type -> vink.kubevm.io.apis.types.WatchRequest
	1, // 9: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Get:output_type -> vink.kubevm.io.apis.types.Subnet
	5, // 10: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.List:output_type -> vink.kubevm.io.apis.types.SubnetList
	1, // 11: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Create:output_type -> vink.kubevm.io.apis.types.Subnet
	1, // 12: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Update:output_type -> vink.kubevm.io.apis.types.Subnet
	6, // 13: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Delete:output_type -> google.protobuf.Empty
	0, // 14: vink.kubevm.io.apis.management.subnet.v1alpha1.SubnetManagement.Watch:output_type -> vink.kubevm.io.apis.management.subnet.v1alpha1.WatchResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_management_subnet_v1alpha1_subnet_proto_init() }
func file_management_subnet_v1alpha1_subnet_proto_init() {
	if File_management_subnet_v1alpha1_subnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_subnet_v1alpha1_subnet_proto_rawDesc), len(file_management_subnet_v1alpha1_subnet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_subnet_v1alpha1_subnet_proto_goTypes,
		DependencyIndexes: file_management_subnet_v1alpha1_subnet_proto_depIdxs,
		MessageInfos:      file_management_subnet_v1alpha1_subnet_proto_msgTypes,
	}.Build()
	File_management_subnet_v1alpha1_subnet_proto = out.File
	file_management_subnet_v1alpha1_subnet_proto_goTypes = nil
	file_management_subnet_v1alpha1_subnet_proto_depIdxs = nil
}
