// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: management/node/v1alpha1/node.proto

package v1alpha1

import (
	context "context"
	types "github.com/kubevm.io/vink/apis/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeManagement_Get_FullMethodName    = "/vink.kubevm.io.apis.management.node.v1alpha1.NodeManagement/Get"
	NodeManagement_List_FullMethodName   = "/vink.kubevm.io.apis.management.node.v1alpha1.NodeManagement/List"
	NodeManagement_Update_FullMethodName = "/vink.kubevm.io.apis.management.node.v1alpha1.NodeManagement/Update"
	NodeManagement_Delete_FullMethodName = "/vink.kubevm.io.apis.management.node.v1alpha1.NodeManagement/Delete"
	NodeManagement_Watch_FullMethodName  = "/vink.kubevm.io.apis.management.node.v1alpha1.NodeManagement/Watch"
)

// NodeManagementClient is the client API for NodeManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeManagementClient interface {
	Get(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*types.Node, error)
	List(ctx context.Context, in *types.ListRequest, opts ...grpc.CallOption) (*types.NodeList, error)
	Update(ctx context.Context, in *types.Node, opts ...grpc.CallOption) (*types.Node, error)
	Delete(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Watch(ctx context.Context, in *types.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type nodeManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeManagementClient(cc grpc.ClientConnInterface) NodeManagementClient {
	return &nodeManagementClient{cc}
}

func (c *nodeManagementClient) Get(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*types.Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Node)
	err := c.cc.Invoke(ctx, NodeManagement_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeManagementClient) List(ctx context.Context, in *types.ListRequest, opts ...grpc.CallOption) (*types.NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.NodeList)
	err := c.cc.Invoke(ctx, NodeManagement_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeManagementClient) Update(ctx context.Context, in *types.Node, opts ...grpc.CallOption) (*types.Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Node)
	err := c.cc.Invoke(ctx, NodeManagement_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeManagementClient) Delete(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeManagement_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeManagementClient) Watch(ctx context.Context, in *types.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeManagement_ServiceDesc.Streams[0], NodeManagement_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[types.WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeManagement_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// NodeManagementServer is the server API for NodeManagement service.
// All implementations must embed UnimplementedNodeManagementServer
// for forward compatibility.
type NodeManagementServer interface {
	Get(context.Context, *types.NamespaceName) (*types.Node, error)
	List(context.Context, *types.ListRequest) (*types.NodeList, error)
	Update(context.Context, *types.Node) (*types.Node, error)
	Delete(context.Context, *types.NamespaceName) (*emptypb.Empty, error)
	Watch(*types.WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedNodeManagementServer()
}

// UnimplementedNodeManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeManagementServer struct{}

func (UnimplementedNodeManagementServer) Get(context.Context, *types.NamespaceName) (*types.Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedNodeManagementServer) List(context.Context, *types.ListRequest) (*types.NodeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNodeManagementServer) Update(context.Context, *types.Node) (*types.Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedNodeManagementServer) Delete(context.Context, *types.NamespaceName) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedNodeManagementServer) Watch(*types.WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedNodeManagementServer) mustEmbedUnimplementedNodeManagementServer() {}
func (UnimplementedNodeManagementServer) testEmbeddedByValue()                        {}

// UnsafeNodeManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeManagementServer will
// result in compilation errors.
type UnsafeNodeManagementServer interface {
	mustEmbedUnimplementedNodeManagementServer()
}

func RegisterNodeManagementServer(s grpc.ServiceRegistrar, srv NodeManagementServer) {
	// If the following call pancis, it indicates UnimplementedNodeManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeManagement_ServiceDesc, srv)
}

func _NodeManagement_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.NamespaceName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagementServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeManagement_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagementServer).Get(ctx, req.(*types.NamespaceName))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeManagement_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagementServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeManagement_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagementServer).List(ctx, req.(*types.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeManagement_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagementServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeManagement_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagementServer).Update(ctx, req.(*types.Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeManagement_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.NamespaceName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagementServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeManagement_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagementServer).Delete(ctx, req.(*types.NamespaceName))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeManagement_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(types.WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeManagementServer).Watch(m, &grpc.GenericServerStream[types.WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeManagement_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// NodeManagement_ServiceDesc is the grpc.ServiceDesc for NodeManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vink.kubevm.io.apis.management.node.v1alpha1.NodeManagement",
	HandlerType: (*NodeManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _NodeManagement_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NodeManagement_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _NodeManagement_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NodeManagement_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _NodeManagement_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "management/node/v1alpha1/node.proto",
}
