// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: management/template_instance/v1alpha1/template_instance.proto

package v1alpha1

import (
	context "context"
	types "github.com/kubevm.io/vink/apis/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemplateInstanceManagement_Get_FullMethodName    = "/vink.kubevm.io.apis.management.templateinstance.v1alpha1.TemplateInstanceManagement/Get"
	TemplateInstanceManagement_List_FullMethodName   = "/vink.kubevm.io.apis.management.templateinstance.v1alpha1.TemplateInstanceManagement/List"
	TemplateInstanceManagement_Create_FullMethodName = "/vink.kubevm.io.apis.management.templateinstance.v1alpha1.TemplateInstanceManagement/Create"
	TemplateInstanceManagement_Update_FullMethodName = "/vink.kubevm.io.apis.management.templateinstance.v1alpha1.TemplateInstanceManagement/Update"
	TemplateInstanceManagement_Delete_FullMethodName = "/vink.kubevm.io.apis.management.templateinstance.v1alpha1.TemplateInstanceManagement/Delete"
	TemplateInstanceManagement_Watch_FullMethodName  = "/vink.kubevm.io.apis.management.templateinstance.v1alpha1.TemplateInstanceManagement/Watch"
)

// TemplateInstanceManagementClient is the client API for TemplateInstanceManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateInstanceManagementClient interface {
	Get(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*types.TemplateInstance, error)
	List(ctx context.Context, in *types.ListRequest, opts ...grpc.CallOption) (*types.TemplateInstanceList, error)
	Create(ctx context.Context, in *types.TemplateInstance, opts ...grpc.CallOption) (*types.TemplateInstance, error)
	Update(ctx context.Context, in *types.TemplateInstance, opts ...grpc.CallOption) (*types.TemplateInstance, error)
	Delete(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Watch(ctx context.Context, in *types.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type templateInstanceManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateInstanceManagementClient(cc grpc.ClientConnInterface) TemplateInstanceManagementClient {
	return &templateInstanceManagementClient{cc}
}

func (c *templateInstanceManagementClient) Get(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*types.TemplateInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.TemplateInstance)
	err := c.cc.Invoke(ctx, TemplateInstanceManagement_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateInstanceManagementClient) List(ctx context.Context, in *types.ListRequest, opts ...grpc.CallOption) (*types.TemplateInstanceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.TemplateInstanceList)
	err := c.cc.Invoke(ctx, TemplateInstanceManagement_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateInstanceManagementClient) Create(ctx context.Context, in *types.TemplateInstance, opts ...grpc.CallOption) (*types.TemplateInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.TemplateInstance)
	err := c.cc.Invoke(ctx, TemplateInstanceManagement_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateInstanceManagementClient) Update(ctx context.Context, in *types.TemplateInstance, opts ...grpc.CallOption) (*types.TemplateInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.TemplateInstance)
	err := c.cc.Invoke(ctx, TemplateInstanceManagement_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateInstanceManagementClient) Delete(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TemplateInstanceManagement_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateInstanceManagementClient) Watch(ctx context.Context, in *types.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TemplateInstanceManagement_ServiceDesc.Streams[0], TemplateInstanceManagement_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[types.WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TemplateInstanceManagement_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// TemplateInstanceManagementServer is the server API for TemplateInstanceManagement service.
// All implementations must embed UnimplementedTemplateInstanceManagementServer
// for forward compatibility.
type TemplateInstanceManagementServer interface {
	Get(context.Context, *types.NamespaceName) (*types.TemplateInstance, error)
	List(context.Context, *types.ListRequest) (*types.TemplateInstanceList, error)
	Create(context.Context, *types.TemplateInstance) (*types.TemplateInstance, error)
	Update(context.Context, *types.TemplateInstance) (*types.TemplateInstance, error)
	Delete(context.Context, *types.NamespaceName) (*emptypb.Empty, error)
	Watch(*types.WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedTemplateInstanceManagementServer()
}

// UnimplementedTemplateInstanceManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplateInstanceManagementServer struct{}

func (UnimplementedTemplateInstanceManagementServer) Get(context.Context, *types.NamespaceName) (*types.TemplateInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTemplateInstanceManagementServer) List(context.Context, *types.ListRequest) (*types.TemplateInstanceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTemplateInstanceManagementServer) Create(context.Context, *types.TemplateInstance) (*types.TemplateInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTemplateInstanceManagementServer) Update(context.Context, *types.TemplateInstance) (*types.TemplateInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTemplateInstanceManagementServer) Delete(context.Context, *types.NamespaceName) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTemplateInstanceManagementServer) Watch(*types.WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedTemplateInstanceManagementServer) mustEmbedUnimplementedTemplateInstanceManagementServer() {
}
func (UnimplementedTemplateInstanceManagementServer) testEmbeddedByValue() {}

// UnsafeTemplateInstanceManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateInstanceManagementServer will
// result in compilation errors.
type UnsafeTemplateInstanceManagementServer interface {
	mustEmbedUnimplementedTemplateInstanceManagementServer()
}

func RegisterTemplateInstanceManagementServer(s grpc.ServiceRegistrar, srv TemplateInstanceManagementServer) {
	// If the following call pancis, it indicates UnimplementedTemplateInstanceManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemplateInstanceManagement_ServiceDesc, srv)
}

func _TemplateInstanceManagement_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.NamespaceName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateInstanceManagementServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateInstanceManagement_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateInstanceManagementServer).Get(ctx, req.(*types.NamespaceName))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateInstanceManagement_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateInstanceManagementServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateInstanceManagement_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateInstanceManagementServer).List(ctx, req.(*types.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateInstanceManagement_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.TemplateInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateInstanceManagementServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateInstanceManagement_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateInstanceManagementServer).Create(ctx, req.(*types.TemplateInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateInstanceManagement_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.TemplateInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateInstanceManagementServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateInstanceManagement_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateInstanceManagementServer).Update(ctx, req.(*types.TemplateInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateInstanceManagement_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.NamespaceName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateInstanceManagementServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateInstanceManagement_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateInstanceManagementServer).Delete(ctx, req.(*types.NamespaceName))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateInstanceManagement_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(types.WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TemplateInstanceManagementServer).Watch(m, &grpc.GenericServerStream[types.WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TemplateInstanceManagement_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// TemplateInstanceManagement_ServiceDesc is the grpc.ServiceDesc for TemplateInstanceManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateInstanceManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vink.kubevm.io.apis.management.templateinstance.v1alpha1.TemplateInstanceManagement",
	HandlerType: (*TemplateInstanceManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TemplateInstanceManagement_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TemplateInstanceManagement_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TemplateInstanceManagement_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TemplateInstanceManagement_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TemplateInstanceManagement_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _TemplateInstanceManagement_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "management/template_instance/v1alpha1/template_instance.proto",
}
