/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	vinkv1alpha1 "github.com/kubevm.io/vink/pkg/k8s/apis/vink/v1alpha1"
	versioned "github.com/kubevm.io/vink/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/kubevm.io/vink/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubevm.io/vink/pkg/k8s/client/listers/vink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualMachineTemplateInformer provides access to a shared informer and lister for
// VirtualMachineTemplates.
type VirtualMachineTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VirtualMachineTemplateLister
}

type virtualMachineTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVirtualMachineTemplateInformer constructs a new informer for VirtualMachineTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualMachineTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineTemplateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualMachineTemplateInformer constructs a new informer for VirtualMachineTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualMachineTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VinkV1alpha1().VirtualMachineTemplates(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VinkV1alpha1().VirtualMachineTemplates(namespace).Watch(context.TODO(), options)
			},
		},
		&vinkv1alpha1.VirtualMachineTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualMachineTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineTemplateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualMachineTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vinkv1alpha1.VirtualMachineTemplate{}, f.defaultInformer)
}

func (f *virtualMachineTemplateInformer) Lister() v1alpha1.VirtualMachineTemplateLister {
	return v1alpha1.NewVirtualMachineTemplateLister(f.Informer().GetIndexer())
}
