/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	vinkv1alpha1 "github.com/kubevm.io/vink/pkg/k8s/apis/vink/v1alpha1"
	versioned "github.com/kubevm.io/vink/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/kubevm.io/vink/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubevm.io/vink/pkg/k8s/client/listers/vink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualMachineSummaryInformer provides access to a shared informer and lister for
// VirtualMachineSummaries.
type VirtualMachineSummaryInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VirtualMachineSummaryLister
}

type virtualMachineSummaryInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVirtualMachineSummaryInformer constructs a new informer for VirtualMachineSummary type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualMachineSummaryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineSummaryInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualMachineSummaryInformer constructs a new informer for VirtualMachineSummary type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualMachineSummaryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VinkV1alpha1().VirtualMachineSummaries(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VinkV1alpha1().VirtualMachineSummaries(namespace).Watch(context.TODO(), options)
			},
		},
		&vinkv1alpha1.VirtualMachineSummary{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualMachineSummaryInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineSummaryInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualMachineSummaryInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vinkv1alpha1.VirtualMachineSummary{}, f.defaultInformer)
}

func (f *virtualMachineSummaryInformer) Lister() v1alpha1.VirtualMachineSummaryLister {
	return v1alpha1.NewVirtualMachineSummaryLister(f.Informer().GetIndexer())
}
