// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: management/virtualmachinesnapshot/v1alpha1/virtualmachinesnapshot.proto

package v1alpha1

import (
	context "context"
	types "github.com/kubevm.io/vink/apis/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VirtualMachineSnapshotManagement_Get_FullMethodName    = "/vink.kubevm.io.apis.management.virtualmachinesnapshot.v1alpha1.VirtualMachineSnapshotManagement/Get"
	VirtualMachineSnapshotManagement_List_FullMethodName   = "/vink.kubevm.io.apis.management.virtualmachinesnapshot.v1alpha1.VirtualMachineSnapshotManagement/List"
	VirtualMachineSnapshotManagement_Create_FullMethodName = "/vink.kubevm.io.apis.management.virtualmachinesnapshot.v1alpha1.VirtualMachineSnapshotManagement/Create"
	VirtualMachineSnapshotManagement_Update_FullMethodName = "/vink.kubevm.io.apis.management.virtualmachinesnapshot.v1alpha1.VirtualMachineSnapshotManagement/Update"
	VirtualMachineSnapshotManagement_Delete_FullMethodName = "/vink.kubevm.io.apis.management.virtualmachinesnapshot.v1alpha1.VirtualMachineSnapshotManagement/Delete"
	VirtualMachineSnapshotManagement_Watch_FullMethodName  = "/vink.kubevm.io.apis.management.virtualmachinesnapshot.v1alpha1.VirtualMachineSnapshotManagement/Watch"
)

// VirtualMachineSnapshotManagementClient is the client API for VirtualMachineSnapshotManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirtualMachineSnapshotManagementClient interface {
	Get(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*types.VirtualMachineSnapshot, error)
	List(ctx context.Context, in *types.ListRequest, opts ...grpc.CallOption) (*types.VirtualMachineSnapshotList, error)
	Create(ctx context.Context, in *types.VirtualMachineSnapshot, opts ...grpc.CallOption) (*types.VirtualMachineSnapshot, error)
	Update(ctx context.Context, in *types.VirtualMachineSnapshot, opts ...grpc.CallOption) (*types.VirtualMachineSnapshot, error)
	Delete(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Watch(ctx context.Context, in *types.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type virtualMachineSnapshotManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualMachineSnapshotManagementClient(cc grpc.ClientConnInterface) VirtualMachineSnapshotManagementClient {
	return &virtualMachineSnapshotManagementClient{cc}
}

func (c *virtualMachineSnapshotManagementClient) Get(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*types.VirtualMachineSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.VirtualMachineSnapshot)
	err := c.cc.Invoke(ctx, VirtualMachineSnapshotManagement_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSnapshotManagementClient) List(ctx context.Context, in *types.ListRequest, opts ...grpc.CallOption) (*types.VirtualMachineSnapshotList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.VirtualMachineSnapshotList)
	err := c.cc.Invoke(ctx, VirtualMachineSnapshotManagement_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSnapshotManagementClient) Create(ctx context.Context, in *types.VirtualMachineSnapshot, opts ...grpc.CallOption) (*types.VirtualMachineSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.VirtualMachineSnapshot)
	err := c.cc.Invoke(ctx, VirtualMachineSnapshotManagement_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSnapshotManagementClient) Update(ctx context.Context, in *types.VirtualMachineSnapshot, opts ...grpc.CallOption) (*types.VirtualMachineSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.VirtualMachineSnapshot)
	err := c.cc.Invoke(ctx, VirtualMachineSnapshotManagement_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSnapshotManagementClient) Delete(ctx context.Context, in *types.NamespaceName, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VirtualMachineSnapshotManagement_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSnapshotManagementClient) Watch(ctx context.Context, in *types.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VirtualMachineSnapshotManagement_ServiceDesc.Streams[0], VirtualMachineSnapshotManagement_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[types.WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VirtualMachineSnapshotManagement_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// VirtualMachineSnapshotManagementServer is the server API for VirtualMachineSnapshotManagement service.
// All implementations must embed UnimplementedVirtualMachineSnapshotManagementServer
// for forward compatibility.
type VirtualMachineSnapshotManagementServer interface {
	Get(context.Context, *types.NamespaceName) (*types.VirtualMachineSnapshot, error)
	List(context.Context, *types.ListRequest) (*types.VirtualMachineSnapshotList, error)
	Create(context.Context, *types.VirtualMachineSnapshot) (*types.VirtualMachineSnapshot, error)
	Update(context.Context, *types.VirtualMachineSnapshot) (*types.VirtualMachineSnapshot, error)
	Delete(context.Context, *types.NamespaceName) (*emptypb.Empty, error)
	Watch(*types.WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedVirtualMachineSnapshotManagementServer()
}

// UnimplementedVirtualMachineSnapshotManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVirtualMachineSnapshotManagementServer struct{}

func (UnimplementedVirtualMachineSnapshotManagementServer) Get(context.Context, *types.NamespaceName) (*types.VirtualMachineSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVirtualMachineSnapshotManagementServer) List(context.Context, *types.ListRequest) (*types.VirtualMachineSnapshotList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedVirtualMachineSnapshotManagementServer) Create(context.Context, *types.VirtualMachineSnapshot) (*types.VirtualMachineSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVirtualMachineSnapshotManagementServer) Update(context.Context, *types.VirtualMachineSnapshot) (*types.VirtualMachineSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedVirtualMachineSnapshotManagementServer) Delete(context.Context, *types.NamespaceName) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVirtualMachineSnapshotManagementServer) Watch(*types.WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedVirtualMachineSnapshotManagementServer) mustEmbedUnimplementedVirtualMachineSnapshotManagementServer() {
}
func (UnimplementedVirtualMachineSnapshotManagementServer) testEmbeddedByValue() {}

// UnsafeVirtualMachineSnapshotManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtualMachineSnapshotManagementServer will
// result in compilation errors.
type UnsafeVirtualMachineSnapshotManagementServer interface {
	mustEmbedUnimplementedVirtualMachineSnapshotManagementServer()
}

func RegisterVirtualMachineSnapshotManagementServer(s grpc.ServiceRegistrar, srv VirtualMachineSnapshotManagementServer) {
	// If the following call pancis, it indicates UnimplementedVirtualMachineSnapshotManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VirtualMachineSnapshotManagement_ServiceDesc, srv)
}

func _VirtualMachineSnapshotManagement_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.NamespaceName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSnapshotManagementServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualMachineSnapshotManagement_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSnapshotManagementServer).Get(ctx, req.(*types.NamespaceName))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSnapshotManagement_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSnapshotManagementServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualMachineSnapshotManagement_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSnapshotManagementServer).List(ctx, req.(*types.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSnapshotManagement_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.VirtualMachineSnapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSnapshotManagementServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualMachineSnapshotManagement_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSnapshotManagementServer).Create(ctx, req.(*types.VirtualMachineSnapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSnapshotManagement_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.VirtualMachineSnapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSnapshotManagementServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualMachineSnapshotManagement_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSnapshotManagementServer).Update(ctx, req.(*types.VirtualMachineSnapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSnapshotManagement_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.NamespaceName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSnapshotManagementServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualMachineSnapshotManagement_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSnapshotManagementServer).Delete(ctx, req.(*types.NamespaceName))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSnapshotManagement_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(types.WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VirtualMachineSnapshotManagementServer).Watch(m, &grpc.GenericServerStream[types.WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VirtualMachineSnapshotManagement_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// VirtualMachineSnapshotManagement_ServiceDesc is the grpc.ServiceDesc for VirtualMachineSnapshotManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtualMachineSnapshotManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vink.kubevm.io.apis.management.virtualmachinesnapshot.v1alpha1.VirtualMachineSnapshotManagement",
	HandlerType: (*VirtualMachineSnapshotManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _VirtualMachineSnapshotManagement_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _VirtualMachineSnapshotManagement_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VirtualMachineSnapshotManagement_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VirtualMachineSnapshotManagement_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VirtualMachineSnapshotManagement_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _VirtualMachineSnapshotManagement_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "management/virtualmachinesnapshot/v1alpha1/virtualmachinesnapshot.proto",
}
