apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: virtualmachinetemplate-vink-webhook
webhooks:
  - name: virtualmachinetemplate.vink.kubevm.io
    rules:
      - apiGroups:
          - vink.kubevm.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - virtualmachinetemplates
    clientConfig:
      # url: https://172.16.1.104:8081/validate-vink-kubevm-io-v1alpha1-virtualmachinetemplate
      url: https://192.168.18.100:8081/validate-vink-kubevm-io-v1alpha1-virtualmachinetemplate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNxRENDQVpBQ0NRQ2toQVVMUHNGRHVEQU5CZ2txaGtpRzl3MEJBUXNGQURBV01SUXdFZ1lEVlFRRERBdHYKY0dWeVlYUnZjaTFqWVRBZUZ3MHlOVEV3TVRjeE5ESXpOVFZhRncwek5URXdNVFV4TkRJek5UVmFNQll4RkRBUwpCZ05WQkFNTUMyOXdaWEpoZEc5eUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUEyVEp6MU4zRVBoS000blBmSjhGOVF4cnRRVHkrQTB1THRCVURPeUV5OUVObTRzVzhrN256Z2pyeG5aQ1YKNlkvSGJpeG9kd29zWlNpR2FHRXpDZDVCR0ovanp0MGxvR0VtQjBpRnNTWVBWditKNGVqRUdiQmRKbjl2MUc3WAp6OTdCL1dPYkNHNFhucUlXdmJvNGpsMHhSOGU3WFB2dzA3aHBWeHBFLzBDUC91STV4dkNDcmVhT2NJWDBkcGdCCnFZYWI4MVlPNVJwRjlKQXVONDRnSitQZWtSM2hnZnd5bEJPSkZkT3JFT3Z4RGZBczFnTU8xT0xSZFY0TERDME4KZGE1MGFvOUpNVC9qS3BOY2FvRkF2UFEvWkpPMFpINktuSm5rbTVFS2I4OG4za3U0ZitQUU5CYzJhd0thNmFFdQo3TmhMRTgzU2JVeXg0NTZMeUhBbFR6UW1TUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQS9yL0N1Ckhwdlhqdms5cnR4YWVBTTVsSm5UUXY0MkxzWlhYZ2NIVkV4N1JDM0lSL0EvR1hCZ1ZYYWE2YUU5R1dTSFlLaWoKZTl5VWdlYlhlc085dXZoaEtBY1E1eWVsTzV6TGYzNFNPTUVUSzI3c1dlOVBkZzkrdHVwWHNtTlloMkZFdmFVVwp4S2xlaTZ0QmJseitHNzJGRDhwUW1xNmdxVGM3OUFRVEVlaDBiTDhRTStSLzlaK1R1ZTd1ckZtL1plblIyR2szClc1endrQ0pwdmlGNjVrU0gyTTFHa1NGUURMd2RNZGdmUTE3S29qYlQ4VWlMTCtuUUdyUnUyL1A1VG1LaTRjc2cKcGRCTE1VQ0pWZVhhZWtveGowRERrYnhZb2VxQU14VUQya1ZTUDJJcERCeXdLS291cWhxSU9QM0QvQUVLVjVvdQpFcXZtZ1VJcEMzWlJWb0VPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: virtualmachinetemplate-vink-webhook
webhooks:
  - name: virtualmachinetemplate.vink.kubevm.io
    rules:
      - apiGroups:
          - vink.kubevm.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - virtualmachinetemplates
    clientConfig:
      # url: https://172.16.1.104:8081/mutate-vink-kubevm-io-v1alpha1-virtualmachinetemplate
      url: https://192.168.18.100:8081/mutate-vink-kubevm-io-v1alpha1-virtualmachinetemplate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNxRENDQVpBQ0NRQ2toQVVMUHNGRHVEQU5CZ2txaGtpRzl3MEJBUXNGQURBV01SUXdFZ1lEVlFRRERBdHYKY0dWeVlYUnZjaTFqWVRBZUZ3MHlOVEV3TVRjeE5ESXpOVFZhRncwek5URXdNVFV4TkRJek5UVmFNQll4RkRBUwpCZ05WQkFNTUMyOXdaWEpoZEc5eUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUEyVEp6MU4zRVBoS000blBmSjhGOVF4cnRRVHkrQTB1THRCVURPeUV5OUVObTRzVzhrN256Z2pyeG5aQ1YKNlkvSGJpeG9kd29zWlNpR2FHRXpDZDVCR0ovanp0MGxvR0VtQjBpRnNTWVBWditKNGVqRUdiQmRKbjl2MUc3WAp6OTdCL1dPYkNHNFhucUlXdmJvNGpsMHhSOGU3WFB2dzA3aHBWeHBFLzBDUC91STV4dkNDcmVhT2NJWDBkcGdCCnFZYWI4MVlPNVJwRjlKQXVONDRnSitQZWtSM2hnZnd5bEJPSkZkT3JFT3Z4RGZBczFnTU8xT0xSZFY0TERDME4KZGE1MGFvOUpNVC9qS3BOY2FvRkF2UFEvWkpPMFpINktuSm5rbTVFS2I4OG4za3U0ZitQUU5CYzJhd0thNmFFdQo3TmhMRTgzU2JVeXg0NTZMeUhBbFR6UW1TUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQS9yL0N1Ckhwdlhqdms5cnR4YWVBTTVsSm5UUXY0MkxzWlhYZ2NIVkV4N1JDM0lSL0EvR1hCZ1ZYYWE2YUU5R1dTSFlLaWoKZTl5VWdlYlhlc085dXZoaEtBY1E1eWVsTzV6TGYzNFNPTUVUSzI3c1dlOVBkZzkrdHVwWHNtTlloMkZFdmFVVwp4S2xlaTZ0QmJseitHNzJGRDhwUW1xNmdxVGM3OUFRVEVlaDBiTDhRTStSLzlaK1R1ZTd1ckZtL1plblIyR2szClc1endrQ0pwdmlGNjVrU0gyTTFHa1NGUURMd2RNZGdmUTE3S29qYlQ4VWlMTCtuUUdyUnUyL1A1VG1LaTRjc2cKcGRCTE1VQ0pWZVhhZWtveGowRERrYnhZb2VxQU14VUQya1ZTUDJJcERCeXdLS291cWhxSU9QM0QvQUVLVjVvdQpFcXZtZ1VJcEMzWlJWb0VPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
---

# apiVersion: admissionregistration.k8s.io/v1
# kind: MutatingWebhookConfiguration
# metadata:
#   name: virtualmachine-vink-webhook
# webhooks:
# - admissionReviewVersions:
#   - v1
#   - v1beta1
#   clientConfig:
#     url: https://172.16.1.104:8081/mutate-kubevirt-io-v1-virtualmachine
#     caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNxRENDQVpBQ0NRREdRT3AwejllanB6QU5CZ2txaGtpRzl3MEJBUXNGQURBV01SUXdFZ1lEVlFRRERBdHYKY0dWeVlYUnZjaTFqWVRBZUZ3MHlOVEE1TURNd05qTTFNalZhRncwek5UQTVNREV3TmpNMU1qVmFNQll4RkRBUwpCZ05WQkFNTUMyOXdaWEpoZEc5eUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUFyRXFWRllqUFBabHV4VktHc1NtM1ZZQXpRcFRKNWVQLzlZVlBCZ3hkRHIzVmpqdXNTNURaUExMaUpveHIKa3FpdnVFZm4xUHl4cnFkaGkwZ3dXZjJkUUVJWU9nQ2tvN0srdk5LSHRpRndLeUxhM3V0VUhWZks5bFE5WktUbwo3UVRSZy9wMUZXVmowYWl1aE9PdFhXL2ozSTV4MUk1c2FNMWliZ2NXNFBSSFZEbi9JM0U4VkFHMWx3RUg3R0xRCnFXZG9CSXVXbFhoL2dRcFlkN1JzbElqQk1aekdyVDJTTlY2RzdzUmVPaGhEVWZXTHd3YnRZR203eWQxVG5YYzcKZUN5M3RUbGtoTG9uSnFhaHI5RDNIUjFiOWlJdm93ZWgvMTljbEt3UFBMbEJaWC9jb2FOeXNUVlErWUhjWnhDVQpHd09ORHkxN2QvZWNNdGxTb3M1Y3hmcDJ0UUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2ZacklTCm9GMHhsSEd6U1ErOUkwUFRhcUM2OHV4YmJENklSV2xJdnVxZjJITXY1S2JSZDhVRmU2QW9KS0c4cWkyRlRBM20KLzZjSEhEVzJSS2tTQU84TDdnK3h2RFdxZU1LSlQvR25PZGNkNmwyOS8zVy9KNitVaXh4S2tZOUx2MXFGb0IyKwpJcXY4L2d4YzVydlFmcjBGQlVWWThhMmtHTHBSeWc1cjJHSTNBbGY5T004WEpOU0wxTnZCb2tHSFp3WXU3ekpyCkxGS2dpUXRyNzlNWHJ0eUloUFQycjk2R0JBVjlrNFBTNGppNEdLdHNWZjJ2Z0ZOeDdOSW0wWGFCZ3ZuVmkwZ1gKT0Z3MWJFNnJrSm9CZlpwNlcxREFTNjI1Z1Q2VjArd3NWWUhOLzVFalB1QzhWSTF2SVcxTHhXOUUxMjNNdWhYTApUMkhjNHVLNFFkb1BicXRiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#   failurePolicy: Fail
#   matchPolicy: Equivalent
#   name: virtualmachine.vink.kubevm.io
#   namespaceSelector: {}
#   objectSelector: {}
#   reinvocationPolicy: IfNeeded
#   rules:
#   - apiGroups:
#     - kubevirt.io
#     apiVersions:
#     - v1alpha3
#     - v1
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - virtualmachines
#     scope: '*'
#   sideEffects: None
#   timeoutSeconds: 10

# webhooks:
#   - name: 00-virtualmachine.vink.kubevm.io
#     rules:
#       - apiGroups:
#           - kubevirt.io
#         apiVersions:
#           - v1
#         operations:
#           - CREATE
#         resources:
#           - virtualmachines
#         scope: '*'
#     clientConfig:
#       url: https://172.16.1.104:8081/mutate-kubevirt-io-v1-virtualmachine
#       caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNxRENDQVpBQ0NRREdRT3AwejllanB6QU5CZ2txaGtpRzl3MEJBUXNGQURBV01SUXdFZ1lEVlFRRERBdHYKY0dWeVlYUnZjaTFqWVRBZUZ3MHlOVEE1TURNd05qTTFNalZhRncwek5UQTVNREV3TmpNMU1qVmFNQll4RkRBUwpCZ05WQkFNTUMyOXdaWEpoZEc5eUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUFyRXFWRllqUFBabHV4VktHc1NtM1ZZQXpRcFRKNWVQLzlZVlBCZ3hkRHIzVmpqdXNTNURaUExMaUpveHIKa3FpdnVFZm4xUHl4cnFkaGkwZ3dXZjJkUUVJWU9nQ2tvN0srdk5LSHRpRndLeUxhM3V0VUhWZks5bFE5WktUbwo3UVRSZy9wMUZXVmowYWl1aE9PdFhXL2ozSTV4MUk1c2FNMWliZ2NXNFBSSFZEbi9JM0U4VkFHMWx3RUg3R0xRCnFXZG9CSXVXbFhoL2dRcFlkN1JzbElqQk1aekdyVDJTTlY2RzdzUmVPaGhEVWZXTHd3YnRZR203eWQxVG5YYzcKZUN5M3RUbGtoTG9uSnFhaHI5RDNIUjFiOWlJdm93ZWgvMTljbEt3UFBMbEJaWC9jb2FOeXNUVlErWUhjWnhDVQpHd09ORHkxN2QvZWNNdGxTb3M1Y3hmcDJ0UUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2ZacklTCm9GMHhsSEd6U1ErOUkwUFRhcUM2OHV4YmJENklSV2xJdnVxZjJITXY1S2JSZDhVRmU2QW9KS0c4cWkyRlRBM20KLzZjSEhEVzJSS2tTQU84TDdnK3h2RFdxZU1LSlQvR25PZGNkNmwyOS8zVy9KNitVaXh4S2tZOUx2MXFGb0IyKwpJcXY4L2d4YzVydlFmcjBGQlVWWThhMmtHTHBSeWc1cjJHSTNBbGY5T004WEpOU0wxTnZCb2tHSFp3WXU3ekpyCkxGS2dpUXRyNzlNWHJ0eUloUFQycjk2R0JBVjlrNFBTNGppNEdLdHNWZjJ2Z0ZOeDdOSW0wWGFCZ3ZuVmkwZ1gKT0Z3MWJFNnJrSm9CZlpwNlcxREFTNjI1Z1Q2VjArd3NWWUhOLzVFalB1QzhWSTF2SVcxTHhXOUUxMjNNdWhYTApUMkhjNHVLNFFkb1BicXRiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#     admissionReviewVersions: ["v1"]
#     failurePolicy: Fail
#     sideEffects: None
