syntax = "proto3";

package vink.kubevm.io.apis.management.virtualmachine.v1alpha1;

import "google/protobuf/empty.proto";
import "types/types.proto";
import "types/virtualmachine.proto";

option go_package = "github.com/kubevm.io/vink/apis/management/virtualmachine/v1alpha1";

service VirtualMachineManagement {
    rpc Get(vink.kubevm.io.apis.types.NamespaceName) returns (vink.kubevm.io.apis.types.VirtualMachine);

    rpc List(vink.kubevm.io.apis.types.ListRequest) returns (vink.kubevm.io.apis.types.VirtualMachineList);

    rpc Create(vink.kubevm.io.apis.types.VirtualMachine) returns (vink.kubevm.io.apis.types.VirtualMachine);

    rpc Update(vink.kubevm.io.apis.types.VirtualMachine) returns (vink.kubevm.io.apis.types.VirtualMachine);

    rpc Delete(vink.kubevm.io.apis.types.NamespaceName) returns (google.protobuf.Empty);

    rpc Watch(vink.kubevm.io.apis.types.WatchRequest) returns (stream WatchResponse);

    rpc PowerState(PowerStateRequest) returns (google.protobuf.Empty);
}

message WatchResponse {
    repeated vink.kubevm.io.apis.types.VirtualMachine added = 1;

    repeated vink.kubevm.io.apis.types.VirtualMachine modified = 2;

    repeated vink.kubevm.io.apis.types.VirtualMachine deleted = 3;
}

message PowerStateRequest {
    enum PowerState {
        UNSPECIFIED = 0;
        ON = 1;
        OFF = 2;
        REBOOT = 3;

        FORCE_OFF = 4;
        FORCE_REBOOT = 5;
    }
    vink.kubevm.io.apis.types.NamespaceName namespace_name = 1;
    PowerState power_state = 2;
}
