/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// TemplateInstanceListerExpansion allows custom methods to be added to
// TemplateInstanceLister.
type TemplateInstanceListerExpansion interface{}

// TemplateInstanceNamespaceListerExpansion allows custom methods to be added to
// TemplateInstanceNamespaceLister.
type TemplateInstanceNamespaceListerExpansion interface{}

// VinkListerExpansion allows custom methods to be added to
// VinkLister.
type VinkListerExpansion interface{}

// VinkNamespaceListerExpansion allows custom methods to be added to
// VinkNamespaceLister.
type VinkNamespaceListerExpansion interface{}

// VirtualMachineClaimListerExpansion allows custom methods to be added to
// VirtualMachineClaimLister.
type VirtualMachineClaimListerExpansion interface{}

// VirtualMachineClaimNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineClaimNamespaceLister.
type VirtualMachineClaimNamespaceListerExpansion interface{}

// VirtualMachineSummaryListerExpansion allows custom methods to be added to
// VirtualMachineSummaryLister.
type VirtualMachineSummaryListerExpansion interface{}

// VirtualMachineSummaryNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineSummaryNamespaceLister.
type VirtualMachineSummaryNamespaceListerExpansion interface{}

// VirtualMachineTemplateListerExpansion allows custom methods to be added to
// VirtualMachineTemplateLister.
type VirtualMachineTemplateListerExpansion interface{}

// VirtualMachineTemplateNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineTemplateNamespaceLister.
type VirtualMachineTemplateNamespaceListerExpansion interface{}
