/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubevm.io/vink/pkg/k8s/apis/vink/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// VinkLister helps list Vinks.
// All objects returned here must be treated as read-only.
type VinkLister interface {
	// List lists all Vinks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Vink, err error)
	// Vinks returns an object that can list and get Vinks.
	Vinks(namespace string) VinkNamespaceLister
	VinkListerExpansion
}

// vinkLister implements the VinkLister interface.
type vinkLister struct {
	listers.ResourceIndexer[*v1alpha1.Vink]
}

// NewVinkLister returns a new VinkLister.
func NewVinkLister(indexer cache.Indexer) VinkLister {
	return &vinkLister{listers.New[*v1alpha1.Vink](indexer, v1alpha1.Resource("vink"))}
}

// Vinks returns an object that can list and get Vinks.
func (s *vinkLister) Vinks(namespace string) VinkNamespaceLister {
	return vinkNamespaceLister{listers.NewNamespaced[*v1alpha1.Vink](s.ResourceIndexer, namespace)}
}

// VinkNamespaceLister helps list and get Vinks.
// All objects returned here must be treated as read-only.
type VinkNamespaceLister interface {
	// List lists all Vinks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Vink, err error)
	// Get retrieves the Vink from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Vink, error)
	VinkNamespaceListerExpansion
}

// vinkNamespaceLister implements the VinkNamespaceLister
// interface.
type vinkNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.Vink]
}
