// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/metadata.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectMeta struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Name                       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GenerateName               *string                `protobuf:"bytes,2,opt,name=generateName,proto3,oneof" json:"generateName,omitempty"`
	Namespace                  *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Finalizers                 []string               `protobuf:"bytes,4,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	Uid                        *string                `protobuf:"bytes,5,opt,name=uid,proto3,oneof" json:"uid,omitempty"`
	ResourceVersion            *string                `protobuf:"bytes,6,opt,name=resourceVersion,proto3,oneof" json:"resourceVersion,omitempty"`
	Generation                 *int64                 `protobuf:"varint,7,opt,name=generation,proto3,oneof" json:"generation,omitempty"`
	CreationTimestamp          *string                `protobuf:"bytes,8,opt,name=creationTimestamp,proto3,oneof" json:"creationTimestamp,omitempty"`
	DeletionTimestamp          *string                `protobuf:"bytes,9,opt,name=deletionTimestamp,proto3,oneof" json:"deletionTimestamp,omitempty"`
	DeletionGracePeriodSeconds *int64                 `protobuf:"varint,10,opt,name=deletionGracePeriodSeconds,proto3,oneof" json:"deletionGracePeriodSeconds,omitempty"`
	Labels                     map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations                map[string]string      `protobuf:"bytes,12,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_types_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_types_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_types_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetGenerateName() string {
	if x != nil && x.GenerateName != nil {
		return *x.GenerateName
	}
	return ""
}

func (x *ObjectMeta) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ObjectMeta) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

func (x *ObjectMeta) GetUid() string {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return ""
}

func (x *ObjectMeta) GetResourceVersion() string {
	if x != nil && x.ResourceVersion != nil {
		return *x.ResourceVersion
	}
	return ""
}

func (x *ObjectMeta) GetGeneration() int64 {
	if x != nil && x.Generation != nil {
		return *x.Generation
	}
	return 0
}

func (x *ObjectMeta) GetCreationTimestamp() string {
	if x != nil && x.CreationTimestamp != nil {
		return *x.CreationTimestamp
	}
	return ""
}

func (x *ObjectMeta) GetDeletionTimestamp() string {
	if x != nil && x.DeletionTimestamp != nil {
		return *x.DeletionTimestamp
	}
	return ""
}

func (x *ObjectMeta) GetDeletionGracePeriodSeconds() int64 {
	if x != nil && x.DeletionGracePeriodSeconds != nil {
		return *x.DeletionGracePeriodSeconds
	}
	return 0
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_types_metadata_proto protoreflect.FileDescriptor

const file_types_metadata_proto_rawDesc = "" +
	"\n" +
	"\x14types/metadata.proto\x12\x19vink.kubevm.io.apis.types\"\xd7\x06\n" +
	"\n" +
	"ObjectMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\fgenerateName\x18\x02 \x01(\tH\x00R\fgenerateName\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x01R\tnamespace\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"finalizers\x18\x04 \x03(\tR\n" +
	"finalizers\x12\x15\n" +
	"\x03uid\x18\x05 \x01(\tH\x02R\x03uid\x88\x01\x01\x12-\n" +
	"\x0fresourceVersion\x18\x06 \x01(\tH\x03R\x0fresourceVersion\x88\x01\x01\x12#\n" +
	"\n" +
	"generation\x18\a \x01(\x03H\x04R\n" +
	"generation\x88\x01\x01\x121\n" +
	"\x11creationTimestamp\x18\b \x01(\tH\x05R\x11creationTimestamp\x88\x01\x01\x121\n" +
	"\x11deletionTimestamp\x18\t \x01(\tH\x06R\x11deletionTimestamp\x88\x01\x01\x12C\n" +
	"\x1adeletionGracePeriodSeconds\x18\n" +
	" \x01(\x03H\aR\x1adeletionGracePeriodSeconds\x88\x01\x01\x12I\n" +
	"\x06labels\x18\v \x03(\v21.vink.kubevm.io.apis.types.ObjectMeta.LabelsEntryR\x06labels\x12X\n" +
	"\vannotations\x18\f \x03(\v26.vink.kubevm.io.apis.types.ObjectMeta.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_generateNameB\f\n" +
	"\n" +
	"_namespaceB\x06\n" +
	"\x04_uidB\x12\n" +
	"\x10_resourceVersionB\r\n" +
	"\v_generationB\x14\n" +
	"\x12_creationTimestampB\x14\n" +
	"\x12_deletionTimestampB\x1d\n" +
	"\x1b_deletionGracePeriodSecondsB&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_metadata_proto_rawDescOnce sync.Once
	file_types_metadata_proto_rawDescData []byte
)

func file_types_metadata_proto_rawDescGZIP() []byte {
	file_types_metadata_proto_rawDescOnce.Do(func() {
		file_types_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_metadata_proto_rawDesc), len(file_types_metadata_proto_rawDesc)))
	})
	return file_types_metadata_proto_rawDescData
}

var file_types_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_metadata_proto_goTypes = []any{
	(*ObjectMeta)(nil), // 0: vink.kubevm.io.apis.types.ObjectMeta
	nil,                // 1: vink.kubevm.io.apis.types.ObjectMeta.LabelsEntry
	nil,                // 2: vink.kubevm.io.apis.types.ObjectMeta.AnnotationsEntry
}
var file_types_metadata_proto_depIdxs = []int32{
	1, // 0: vink.kubevm.io.apis.types.ObjectMeta.labels:type_name -> vink.kubevm.io.apis.types.ObjectMeta.LabelsEntry
	2, // 1: vink.kubevm.io.apis.types.ObjectMeta.annotations:type_name -> vink.kubevm.io.apis.types.ObjectMeta.AnnotationsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_metadata_proto_init() }
func file_types_metadata_proto_init() {
	if File_types_metadata_proto != nil {
		return
	}
	file_types_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_metadata_proto_rawDesc), len(file_types_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_metadata_proto_goTypes,
		DependencyIndexes: file_types_metadata_proto_depIdxs,
		MessageInfos:      file_types_metadata_proto_msgTypes,
	}.Build()
	File_types_metadata_proto = out.File
	file_types_metadata_proto_goTypes = nil
	file_types_metadata_proto_depIdxs = nil
}
