// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: types/nad.proto

package types

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NetworkAttachmentDefinition with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NetworkAttachmentDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NetworkAttachmentDefinition with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NetworkAttachmentDefinitionMultiError, or nil if none found.
func (m *NetworkAttachmentDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *NetworkAttachmentDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Kind

	// no validation rules for ApiVersion

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NetworkAttachmentDefinitionValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NetworkAttachmentDefinitionValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NetworkAttachmentDefinitionValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSpec()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NetworkAttachmentDefinitionValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NetworkAttachmentDefinitionValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpec()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NetworkAttachmentDefinitionValidationError{
				field:  "Spec",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return NetworkAttachmentDefinitionMultiError(errors)
	}

	return nil
}

// NetworkAttachmentDefinitionMultiError is an error wrapping multiple
// validation errors returned by NetworkAttachmentDefinition.ValidateAll() if
// the designated constraints aren't met.
type NetworkAttachmentDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NetworkAttachmentDefinitionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NetworkAttachmentDefinitionMultiError) AllErrors() []error { return m }

// NetworkAttachmentDefinitionValidationError is the validation error returned
// by NetworkAttachmentDefinition.Validate if the designated constraints
// aren't met.
type NetworkAttachmentDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NetworkAttachmentDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NetworkAttachmentDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NetworkAttachmentDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NetworkAttachmentDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NetworkAttachmentDefinitionValidationError) ErrorName() string {
	return "NetworkAttachmentDefinitionValidationError"
}

// Error satisfies the builtin error interface
func (e NetworkAttachmentDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNetworkAttachmentDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NetworkAttachmentDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NetworkAttachmentDefinitionValidationError{}

// Validate checks the field values on NetworkAttachmentDefinitionList with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NetworkAttachmentDefinitionList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NetworkAttachmentDefinitionList with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// NetworkAttachmentDefinitionListMultiError, or nil if none found.
func (m *NetworkAttachmentDefinitionList) ValidateAll() error {
	return m.validate(true)
}

func (m *NetworkAttachmentDefinitionList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, NetworkAttachmentDefinitionListValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, NetworkAttachmentDefinitionListValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return NetworkAttachmentDefinitionListValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return NetworkAttachmentDefinitionListMultiError(errors)
	}

	return nil
}

// NetworkAttachmentDefinitionListMultiError is an error wrapping multiple
// validation errors returned by NetworkAttachmentDefinitionList.ValidateAll()
// if the designated constraints aren't met.
type NetworkAttachmentDefinitionListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NetworkAttachmentDefinitionListMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NetworkAttachmentDefinitionListMultiError) AllErrors() []error { return m }

// NetworkAttachmentDefinitionListValidationError is the validation error
// returned by NetworkAttachmentDefinitionList.Validate if the designated
// constraints aren't met.
type NetworkAttachmentDefinitionListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NetworkAttachmentDefinitionListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NetworkAttachmentDefinitionListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NetworkAttachmentDefinitionListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NetworkAttachmentDefinitionListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NetworkAttachmentDefinitionListValidationError) ErrorName() string {
	return "NetworkAttachmentDefinitionListValidationError"
}

// Error satisfies the builtin error interface
func (e NetworkAttachmentDefinitionListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNetworkAttachmentDefinitionList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NetworkAttachmentDefinitionListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NetworkAttachmentDefinitionListValidationError{}

// Validate checks the field values on NetworkAttachmentDefinitionSpec with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NetworkAttachmentDefinitionSpec) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NetworkAttachmentDefinitionSpec with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// NetworkAttachmentDefinitionSpecMultiError, or nil if none found.
func (m *NetworkAttachmentDefinitionSpec) ValidateAll() error {
	return m.validate(true)
}

func (m *NetworkAttachmentDefinitionSpec) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Config

	if len(errors) > 0 {
		return NetworkAttachmentDefinitionSpecMultiError(errors)
	}

	return nil
}

// NetworkAttachmentDefinitionSpecMultiError is an error wrapping multiple
// validation errors returned by NetworkAttachmentDefinitionSpec.ValidateAll()
// if the designated constraints aren't met.
type NetworkAttachmentDefinitionSpecMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NetworkAttachmentDefinitionSpecMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NetworkAttachmentDefinitionSpecMultiError) AllErrors() []error { return m }

// NetworkAttachmentDefinitionSpecValidationError is the validation error
// returned by NetworkAttachmentDefinitionSpec.Validate if the designated
// constraints aren't met.
type NetworkAttachmentDefinitionSpecValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NetworkAttachmentDefinitionSpecValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NetworkAttachmentDefinitionSpecValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NetworkAttachmentDefinitionSpecValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NetworkAttachmentDefinitionSpecValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NetworkAttachmentDefinitionSpecValidationError) ErrorName() string {
	return "NetworkAttachmentDefinitionSpecValidationError"
}

// Error satisfies the builtin error interface
func (e NetworkAttachmentDefinitionSpecValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNetworkAttachmentDefinitionSpec.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NetworkAttachmentDefinitionSpecValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NetworkAttachmentDefinitionSpecValidationError{}
