// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using NetworkAttachmentDefinition within kubernetes types, where deepcopy-gen is used.
func (in *NetworkAttachmentDefinition) DeepCopyInto(out *NetworkAttachmentDefinition) {
	p := proto.Clone(in).(*NetworkAttachmentDefinition)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAttachmentDefinition. Required by controller-gen.
func (in *NetworkAttachmentDefinition) DeepCopy() *NetworkAttachmentDefinition {
	if in == nil {
		return nil
	}
	out := new(NetworkAttachmentDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAttachmentDefinition. Required by controller-gen.
func (in *NetworkAttachmentDefinition) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkAttachmentDefinitionList within kubernetes types, where deepcopy-gen is used.
func (in *NetworkAttachmentDefinitionList) DeepCopyInto(out *NetworkAttachmentDefinitionList) {
	p := proto.Clone(in).(*NetworkAttachmentDefinitionList)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAttachmentDefinitionList. Required by controller-gen.
func (in *NetworkAttachmentDefinitionList) DeepCopy() *NetworkAttachmentDefinitionList {
	if in == nil {
		return nil
	}
	out := new(NetworkAttachmentDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAttachmentDefinitionList. Required by controller-gen.
func (in *NetworkAttachmentDefinitionList) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkAttachmentDefinitionSpec within kubernetes types, where deepcopy-gen is used.
func (in *NetworkAttachmentDefinitionSpec) DeepCopyInto(out *NetworkAttachmentDefinitionSpec) {
	p := proto.Clone(in).(*NetworkAttachmentDefinitionSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAttachmentDefinitionSpec. Required by controller-gen.
func (in *NetworkAttachmentDefinitionSpec) DeepCopy() *NetworkAttachmentDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkAttachmentDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAttachmentDefinitionSpec. Required by controller-gen.
func (in *NetworkAttachmentDefinitionSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
