// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Namespace within kubernetes types, where deepcopy-gen is used.
func (in *Namespace) DeepCopyInto(out *Namespace) {
	p := proto.Clone(in).(*Namespace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopy() *Namespace {
	if in == nil {
		return nil
	}
	out := new(Namespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NamespaceList within kubernetes types, where deepcopy-gen is used.
func (in *NamespaceList) DeepCopyInto(out *NamespaceList) {
	p := proto.Clone(in).(*NamespaceList)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceList. Required by controller-gen.
func (in *NamespaceList) DeepCopy() *NamespaceList {
	if in == nil {
		return nil
	}
	out := new(NamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceList. Required by controller-gen.
func (in *NamespaceList) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NamespaceSpec within kubernetes types, where deepcopy-gen is used.
func (in *NamespaceSpec) DeepCopyInto(out *NamespaceSpec) {
	p := proto.Clone(in).(*NamespaceSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSpec. Required by controller-gen.
func (in *NamespaceSpec) DeepCopy() *NamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSpec. Required by controller-gen.
func (in *NamespaceSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NamespaceStatus within kubernetes types, where deepcopy-gen is used.
func (in *NamespaceStatus) DeepCopyInto(out *NamespaceStatus) {
	p := proto.Clone(in).(*NamespaceStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceStatus. Required by controller-gen.
func (in *NamespaceStatus) DeepCopy() *NamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceStatus. Required by controller-gen.
func (in *NamespaceStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
