// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/namespace.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Metadata      *ObjectMeta            `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *NamespaceSpec         `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *NamespaceStatus       `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_types_namespace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_types_namespace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_types_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Namespace) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Namespace) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Namespace) GetSpec() *NamespaceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Namespace) GetStatus() *NamespaceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type NamespaceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Namespace           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceList) Reset() {
	*x = NamespaceList{}
	mi := &file_types_namespace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceList) ProtoMessage() {}

func (x *NamespaceList) ProtoReflect() protoreflect.Message {
	mi := &file_types_namespace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceList.ProtoReflect.Descriptor instead.
func (*NamespaceList) Descriptor() ([]byte, []int) {
	return file_types_namespace_proto_rawDescGZIP(), []int{1}
}

func (x *NamespaceList) GetItems() []*Namespace {
	if x != nil {
		return x.Items
	}
	return nil
}

type NamespaceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceSpec) Reset() {
	*x = NamespaceSpec{}
	mi := &file_types_namespace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceSpec) ProtoMessage() {}

func (x *NamespaceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_namespace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceSpec.ProtoReflect.Descriptor instead.
func (*NamespaceSpec) Descriptor() ([]byte, []int) {
	return file_types_namespace_proto_rawDescGZIP(), []int{2}
}

type NamespaceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceStatus) Reset() {
	*x = NamespaceStatus{}
	mi := &file_types_namespace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceStatus) ProtoMessage() {}

func (x *NamespaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_namespace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceStatus.ProtoReflect.Descriptor instead.
func (*NamespaceStatus) Descriptor() ([]byte, []int) {
	return file_types_namespace_proto_rawDescGZIP(), []int{3}
}

var File_types_namespace_proto protoreflect.FileDescriptor

const file_types_namespace_proto_rawDesc = "" +
	"\n" +
	"\x15types/namespace.proto\x12\x19vink.kubevm.io.apis.types\x1a\x14types/metadata.proto\"\x84\x02\n" +
	"\tNamespace\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12A\n" +
	"\bmetadata\x18\x03 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12<\n" +
	"\x04spec\x18\x04 \x01(\v2(.vink.kubevm.io.apis.types.NamespaceSpecR\x04spec\x12B\n" +
	"\x06status\x18\x05 \x01(\v2*.vink.kubevm.io.apis.types.NamespaceStatusR\x06status\"K\n" +
	"\rNamespaceList\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.vink.kubevm.io.apis.types.NamespaceR\x05items\"\x0f\n" +
	"\rNamespaceSpec\"\x11\n" +
	"\x0fNamespaceStatusB&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_namespace_proto_rawDescOnce sync.Once
	file_types_namespace_proto_rawDescData []byte
)

func file_types_namespace_proto_rawDescGZIP() []byte {
	file_types_namespace_proto_rawDescOnce.Do(func() {
		file_types_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_namespace_proto_rawDesc), len(file_types_namespace_proto_rawDesc)))
	})
	return file_types_namespace_proto_rawDescData
}

var file_types_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_namespace_proto_goTypes = []any{
	(*Namespace)(nil),       // 0: vink.kubevm.io.apis.types.Namespace
	(*NamespaceList)(nil),   // 1: vink.kubevm.io.apis.types.NamespaceList
	(*NamespaceSpec)(nil),   // 2: vink.kubevm.io.apis.types.NamespaceSpec
	(*NamespaceStatus)(nil), // 3: vink.kubevm.io.apis.types.NamespaceStatus
	(*ObjectMeta)(nil),      // 4: vink.kubevm.io.apis.types.ObjectMeta
}
var file_types_namespace_proto_depIdxs = []int32{
	4, // 0: vink.kubevm.io.apis.types.Namespace.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	2, // 1: vink.kubevm.io.apis.types.Namespace.spec:type_name -> vink.kubevm.io.apis.types.NamespaceSpec
	3, // 2: vink.kubevm.io.apis.types.Namespace.status:type_name -> vink.kubevm.io.apis.types.NamespaceStatus
	0, // 3: vink.kubevm.io.apis.types.NamespaceList.items:type_name -> vink.kubevm.io.apis.types.Namespace
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_types_namespace_proto_init() }
func file_types_namespace_proto_init() {
	if File_types_namespace_proto != nil {
		return
	}
	file_types_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_namespace_proto_rawDesc), len(file_types_namespace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_namespace_proto_goTypes,
		DependencyIndexes: file_types_namespace_proto_depIdxs,
		MessageInfos:      file_types_namespace_proto_msgTypes,
	}.Build()
	File_types_namespace_proto = out.File
	file_types_namespace_proto_goTypes = nil
	file_types_namespace_proto_depIdxs = nil
}
