// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/sc.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageClass struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion        string                 `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Metadata          *ObjectMeta            `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Parameters        map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Provisioner       string                 `protobuf:"bytes,5,opt,name=provisioner,proto3" json:"provisioner,omitempty"`
	ReclaimPolicy     string                 `protobuf:"bytes,6,opt,name=reclaimPolicy,proto3" json:"reclaimPolicy,omitempty"`
	VolumeBindingMode string                 `protobuf:"bytes,7,opt,name=volumeBindingMode,proto3" json:"volumeBindingMode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StorageClass) Reset() {
	*x = StorageClass{}
	mi := &file_types_sc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageClass) ProtoMessage() {}

func (x *StorageClass) ProtoReflect() protoreflect.Message {
	mi := &file_types_sc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageClass.ProtoReflect.Descriptor instead.
func (*StorageClass) Descriptor() ([]byte, []int) {
	return file_types_sc_proto_rawDescGZIP(), []int{0}
}

func (x *StorageClass) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StorageClass) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *StorageClass) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StorageClass) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StorageClass) GetProvisioner() string {
	if x != nil {
		return x.Provisioner
	}
	return ""
}

func (x *StorageClass) GetReclaimPolicy() string {
	if x != nil {
		return x.ReclaimPolicy
	}
	return ""
}

func (x *StorageClass) GetVolumeBindingMode() string {
	if x != nil {
		return x.VolumeBindingMode
	}
	return ""
}

type StorageClassList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StorageClass        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageClassList) Reset() {
	*x = StorageClassList{}
	mi := &file_types_sc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageClassList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageClassList) ProtoMessage() {}

func (x *StorageClassList) ProtoReflect() protoreflect.Message {
	mi := &file_types_sc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageClassList.ProtoReflect.Descriptor instead.
func (*StorageClassList) Descriptor() ([]byte, []int) {
	return file_types_sc_proto_rawDescGZIP(), []int{1}
}

func (x *StorageClassList) GetItems() []*StorageClass {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_types_sc_proto protoreflect.FileDescriptor

const file_types_sc_proto_rawDesc = "" +
	"\n" +
	"\x0etypes/sc.proto\x12\x19vink.kubevm.io.apis.types\x1a\x14types/metadata.proto\"\x93\x03\n" +
	"\fStorageClass\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12A\n" +
	"\bmetadata\x18\x03 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12W\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v27.vink.kubevm.io.apis.types.StorageClass.ParametersEntryR\n" +
	"parameters\x12 \n" +
	"\vprovisioner\x18\x05 \x01(\tR\vprovisioner\x12$\n" +
	"\rreclaimPolicy\x18\x06 \x01(\tR\rreclaimPolicy\x12,\n" +
	"\x11volumeBindingMode\x18\a \x01(\tR\x11volumeBindingMode\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x10StorageClassList\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.vink.kubevm.io.apis.types.StorageClassR\x05itemsB&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_sc_proto_rawDescOnce sync.Once
	file_types_sc_proto_rawDescData []byte
)

func file_types_sc_proto_rawDescGZIP() []byte {
	file_types_sc_proto_rawDescOnce.Do(func() {
		file_types_sc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_sc_proto_rawDesc), len(file_types_sc_proto_rawDesc)))
	})
	return file_types_sc_proto_rawDescData
}

var file_types_sc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_sc_proto_goTypes = []any{
	(*StorageClass)(nil),     // 0: vink.kubevm.io.apis.types.StorageClass
	(*StorageClassList)(nil), // 1: vink.kubevm.io.apis.types.StorageClassList
	nil,                      // 2: vink.kubevm.io.apis.types.StorageClass.ParametersEntry
	(*ObjectMeta)(nil),       // 3: vink.kubevm.io.apis.types.ObjectMeta
}
var file_types_sc_proto_depIdxs = []int32{
	3, // 0: vink.kubevm.io.apis.types.StorageClass.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	2, // 1: vink.kubevm.io.apis.types.StorageClass.parameters:type_name -> vink.kubevm.io.apis.types.StorageClass.ParametersEntry
	0, // 2: vink.kubevm.io.apis.types.StorageClassList.items:type_name -> vink.kubevm.io.apis.types.StorageClass
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_types_sc_proto_init() }
func file_types_sc_proto_init() {
	if File_types_sc_proto != nil {
		return
	}
	file_types_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_sc_proto_rawDesc), len(file_types_sc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_sc_proto_goTypes,
		DependencyIndexes: file_types_sc_proto_depIdxs,
		MessageInfos:      file_types_sc_proto_msgTypes,
	}.Build()
	File_types_sc_proto = out.File
	file_types_sc_proto_goTypes = nil
	file_types_sc_proto_depIdxs = nil
}
