// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using StorageClass within kubernetes types, where deepcopy-gen is used.
func (in *StorageClass) DeepCopyInto(out *StorageClass) {
	p := proto.Clone(in).(*StorageClass)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClass. Required by controller-gen.
func (in *StorageClass) DeepCopy() *StorageClass {
	if in == nil {
		return nil
	}
	out := new(StorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new StorageClass. Required by controller-gen.
func (in *StorageClass) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using StorageClassList within kubernetes types, where deepcopy-gen is used.
func (in *StorageClassList) DeepCopyInto(out *StorageClassList) {
	p := proto.Clone(in).(*StorageClassList)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassList. Required by controller-gen.
func (in *StorageClassList) DeepCopy() *StorageClassList {
	if in == nil {
		return nil
	}
	out := new(StorageClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassList. Required by controller-gen.
func (in *StorageClassList) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
