// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceType int32

const (
	ResourceType_UNSPECIFIED              ResourceType = 0
	ResourceType_VIRTUAL_MACHINE          ResourceType = 1
	ResourceType_VIRTUAL_MACHINE_INSTANCE ResourceType = 2
	ResourceType_DATA_VOLUME              ResourceType = 3
	ResourceType_NODE                     ResourceType = 4
	ResourceType_NAMESPACE                ResourceType = 5
	ResourceType_MULTUS                   ResourceType = 6
	ResourceType_SUBNET                   ResourceType = 7
	ResourceType_VPC                      ResourceType = 8
	ResourceType_IPPOOL                   ResourceType = 9
	ResourceType_STORAGE_CLASS            ResourceType = 10
	ResourceType_IPS                      ResourceType = 11
	ResourceType_VIRTUAL_MACHINE_SUMMARY  ResourceType = 12
	ResourceType_EVENT                    ResourceType = 13
	ResourceType_VIRTUAL_MACHINE_SNAPSHOT ResourceType = 14
	ResourceType_VIRTUAL_MACHINE_RESTORE  ResourceType = 15
	ResourceType_VIRTUAL_MACHINE_CLONE    ResourceType = 16
	ResourceType_PROVIDER_NETWORK         ResourceType = 17
	ResourceType_VLAN                     ResourceType = 18
	ResourceType_VIRTUAL_MACHINE_POOL     ResourceType = 19
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "VIRTUAL_MACHINE",
		2:  "VIRTUAL_MACHINE_INSTANCE",
		3:  "DATA_VOLUME",
		4:  "NODE",
		5:  "NAMESPACE",
		6:  "MULTUS",
		7:  "SUBNET",
		8:  "VPC",
		9:  "IPPOOL",
		10: "STORAGE_CLASS",
		11: "IPS",
		12: "VIRTUAL_MACHINE_SUMMARY",
		13: "EVENT",
		14: "VIRTUAL_MACHINE_SNAPSHOT",
		15: "VIRTUAL_MACHINE_RESTORE",
		16: "VIRTUAL_MACHINE_CLONE",
		17: "PROVIDER_NETWORK",
		18: "VLAN",
		19: "VIRTUAL_MACHINE_POOL",
	}
	ResourceType_value = map[string]int32{
		"UNSPECIFIED":              0,
		"VIRTUAL_MACHINE":          1,
		"VIRTUAL_MACHINE_INSTANCE": 2,
		"DATA_VOLUME":              3,
		"NODE":                     4,
		"NAMESPACE":                5,
		"MULTUS":                   6,
		"SUBNET":                   7,
		"VPC":                      8,
		"IPPOOL":                   9,
		"STORAGE_CLASS":            10,
		"IPS":                      11,
		"VIRTUAL_MACHINE_SUMMARY":  12,
		"EVENT":                    13,
		"VIRTUAL_MACHINE_SNAPSHOT": 14,
		"VIRTUAL_MACHINE_RESTORE":  15,
		"VIRTUAL_MACHINE_CLONE":    16,
		"PROVIDER_NETWORK":         17,
		"VLAN":                     18,
		"VIRTUAL_MACHINE_POOL":     19,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_types_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_types_types_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{0}
}

type NamespaceName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceName) Reset() {
	*x = NamespaceName{}
	mi := &file_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceName) ProtoMessage() {}

func (x *NamespaceName) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceName.ProtoReflect.Descriptor instead.
func (*NamespaceName) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *NamespaceName) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespaceName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FieldSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPath     string                 `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	JsonPath      string                 `protobuf:"bytes,4,opt,name=json_path,json=jsonPath,proto3" json:"json_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSelector) Reset() {
	*x = FieldSelector{}
	mi := &file_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSelector) ProtoMessage() {}

func (x *FieldSelector) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSelector.ProtoReflect.Descriptor instead.
func (*FieldSelector) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *FieldSelector) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *FieldSelector) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *FieldSelector) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *FieldSelector) GetJsonPath() string {
	if x != nil {
		return x.JsonPath
	}
	return ""
}

type FieldSelectorGroup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Operator       string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	FieldSelectors []*FieldSelector       `protobuf:"bytes,2,rep,name=field_selectors,json=fieldSelectors,proto3" json:"field_selectors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FieldSelectorGroup) Reset() {
	*x = FieldSelectorGroup{}
	mi := &file_types_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSelectorGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSelectorGroup) ProtoMessage() {}

func (x *FieldSelectorGroup) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSelectorGroup.ProtoReflect.Descriptor instead.
func (*FieldSelectorGroup) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{2}
}

func (x *FieldSelectorGroup) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *FieldSelectorGroup) GetFieldSelectors() []*FieldSelector {
	if x != nil {
		return x.FieldSelectors
	}
	return nil
}

type OperatingSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatingSystem) Reset() {
	*x = OperatingSystem{}
	mi := &file_types_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatingSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingSystem) ProtoMessage() {}

func (x *OperatingSystem) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatingSystem.ProtoReflect.Descriptor instead.
func (*OperatingSystem) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{3}
}

func (x *OperatingSystem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperatingSystem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_types_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_types_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{5}
}

func (x *WatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Condition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastTransitionTime string                 `protobuf:"bytes,5,opt,name=lastTransitionTime,proto3" json:"lastTransitionTime,omitempty"`
	LastProbeTime      string                 `protobuf:"bytes,6,opt,name=lastProbeTime,proto3" json:"lastProbeTime,omitempty"`
	LastHeartbeatTime  string                 `protobuf:"bytes,7,opt,name=lastHeartbeatTime,proto3" json:"lastHeartbeatTime,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_types_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{6}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Condition) GetLastTransitionTime() string {
	if x != nil {
		return x.LastTransitionTime
	}
	return ""
}

func (x *Condition) GetLastProbeTime() string {
	if x != nil {
		return x.LastProbeTime
	}
	return ""
}

func (x *Condition) GetLastHeartbeatTime() string {
	if x != nil {
		return x.LastHeartbeatTime
	}
	return ""
}

var File_types_types_proto protoreflect.FileDescriptor

const file_types_types_proto_rawDesc = "" +
	"\n" +
	"\x11types/types.proto\x12\x19vink.kubevm.io.apis.types\"A\n" +
	"\rNamespaceName\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x7f\n" +
	"\rFieldSelector\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\x12\x1b\n" +
	"\tjson_path\x18\x04 \x01(\tR\bjsonPath\"\x83\x01\n" +
	"\x12FieldSelectorGroup\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12Q\n" +
	"\x0ffield_selectors\x18\x02 \x03(\v2(.vink.kubevm.io.apis.types.FieldSelectorR\x0efieldSelectors\"?\n" +
	"\x0fOperatingSystem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"?\n" +
	"\vListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\fWatchRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xed\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12.\n" +
	"\x12lastTransitionTime\x18\x05 \x01(\tR\x12lastTransitionTime\x12$\n" +
	"\rlastProbeTime\x18\x06 \x01(\tR\rlastProbeTime\x12,\n" +
	"\x11lastHeartbeatTime\x18\a \x01(\tR\x11lastHeartbeatTime*\xfd\x02\n" +
	"\fResourceType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fVIRTUAL_MACHINE\x10\x01\x12\x1c\n" +
	"\x18VIRTUAL_MACHINE_INSTANCE\x10\x02\x12\x0f\n" +
	"\vDATA_VOLUME\x10\x03\x12\b\n" +
	"\x04NODE\x10\x04\x12\r\n" +
	"\tNAMESPACE\x10\x05\x12\n" +
	"\n" +
	"\x06MULTUS\x10\x06\x12\n" +
	"\n" +
	"\x06SUBNET\x10\a\x12\a\n" +
	"\x03VPC\x10\b\x12\n" +
	"\n" +
	"\x06IPPOOL\x10\t\x12\x11\n" +
	"\rSTORAGE_CLASS\x10\n" +
	"\x12\a\n" +
	"\x03IPS\x10\v\x12\x1b\n" +
	"\x17VIRTUAL_MACHINE_SUMMARY\x10\f\x12\t\n" +
	"\x05EVENT\x10\r\x12\x1c\n" +
	"\x18VIRTUAL_MACHINE_SNAPSHOT\x10\x0e\x12\x1b\n" +
	"\x17VIRTUAL_MACHINE_RESTORE\x10\x0f\x12\x19\n" +
	"\x15VIRTUAL_MACHINE_CLONE\x10\x10\x12\x14\n" +
	"\x10PROVIDER_NETWORK\x10\x11\x12\b\n" +
	"\x04VLAN\x10\x12\x12\x18\n" +
	"\x14VIRTUAL_MACHINE_POOL\x10\x13B&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_types_proto_rawDescOnce sync.Once
	file_types_types_proto_rawDescData []byte
)

func file_types_types_proto_rawDescGZIP() []byte {
	file_types_types_proto_rawDescOnce.Do(func() {
		file_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_types_proto_rawDesc), len(file_types_types_proto_rawDesc)))
	})
	return file_types_types_proto_rawDescData
}

var file_types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_types_types_proto_goTypes = []any{
	(ResourceType)(0),          // 0: vink.kubevm.io.apis.types.ResourceType
	(*NamespaceName)(nil),      // 1: vink.kubevm.io.apis.types.NamespaceName
	(*FieldSelector)(nil),      // 2: vink.kubevm.io.apis.types.FieldSelector
	(*FieldSelectorGroup)(nil), // 3: vink.kubevm.io.apis.types.FieldSelectorGroup
	(*OperatingSystem)(nil),    // 4: vink.kubevm.io.apis.types.OperatingSystem
	(*ListRequest)(nil),        // 5: vink.kubevm.io.apis.types.ListRequest
	(*WatchRequest)(nil),       // 6: vink.kubevm.io.apis.types.WatchRequest
	(*Condition)(nil),          // 7: vink.kubevm.io.apis.types.Condition
}
var file_types_types_proto_depIdxs = []int32{
	2, // 0: vink.kubevm.io.apis.types.FieldSelectorGroup.field_selectors:type_name -> vink.kubevm.io.apis.types.FieldSelector
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_types_proto_init() }
func file_types_types_proto_init() {
	if File_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_types_proto_rawDesc), len(file_types_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_types_proto_goTypes,
		DependencyIndexes: file_types_types_proto_depIdxs,
		EnumInfos:         file_types_types_proto_enumTypes,
		MessageInfos:      file_types_types_proto_msgTypes,
	}.Build()
	File_types_types_proto = out.File
	file_types_types_proto_goTypes = nil
	file_types_types_proto_depIdxs = nil
}
