// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/virtualmachine.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Metadata      *ObjectMeta            `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *VirtualMachineSpec    `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VirtualMachineStatus  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachine) Reset() {
	*x = VirtualMachine{}
	mi := &file_types_virtualmachine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachine) ProtoMessage() {}

func (x *VirtualMachine) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachine.ProtoReflect.Descriptor instead.
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachine) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VirtualMachine) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *VirtualMachine) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VirtualMachine) GetSpec() *VirtualMachineSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *VirtualMachine) GetStatus() *VirtualMachineStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type VirtualMachineSpec struct {
	state               protoimpl.MessageState              `protogen:"open.v1"`
	RunStrategy         string                              `protobuf:"bytes,1,opt,name=runStrategy,proto3" json:"runStrategy,omitempty"`
	Template            *VirtualMachineInstanceTemplateSpec `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	DataVolumeTemplates []*DataVolumeTemplate               `protobuf:"bytes,3,rep,name=dataVolumeTemplates,proto3" json:"dataVolumeTemplates,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VirtualMachineSpec) Reset() {
	*x = VirtualMachineSpec{}
	mi := &file_types_virtualmachine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineSpec) ProtoMessage() {}

func (x *VirtualMachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineSpec.ProtoReflect.Descriptor instead.
func (*VirtualMachineSpec) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualMachineSpec) GetRunStrategy() string {
	if x != nil {
		return x.RunStrategy
	}
	return ""
}

func (x *VirtualMachineSpec) GetTemplate() *VirtualMachineInstanceTemplateSpec {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *VirtualMachineSpec) GetDataVolumeTemplates() []*DataVolumeTemplate {
	if x != nil {
		return x.DataVolumeTemplates
	}
	return nil
}

type VirtualMachineStatus struct {
	state                  protoimpl.MessageState                       `protogen:"open.v1"`
	Ready                  bool                                         `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	PrintableStatus        string                                       `protobuf:"bytes,2,opt,name=printableStatus,proto3" json:"printableStatus,omitempty"`
	RunStrategy            string                                       `protobuf:"bytes,3,opt,name=runStrategy,proto3" json:"runStrategy,omitempty"`
	Created                bool                                         `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Conditions             []*Condition                                 `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	VolumeSnapshotStatuses []*VirtualMachineStatus_VolumeSnapshotStatus `protobuf:"bytes,6,rep,name=volumeSnapshotStatuses,proto3" json:"volumeSnapshotStatuses,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VirtualMachineStatus) Reset() {
	*x = VirtualMachineStatus{}
	mi := &file_types_virtualmachine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineStatus) ProtoMessage() {}

func (x *VirtualMachineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineStatus.ProtoReflect.Descriptor instead.
func (*VirtualMachineStatus) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualMachineStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *VirtualMachineStatus) GetPrintableStatus() string {
	if x != nil {
		return x.PrintableStatus
	}
	return ""
}

func (x *VirtualMachineStatus) GetRunStrategy() string {
	if x != nil {
		return x.RunStrategy
	}
	return ""
}

func (x *VirtualMachineStatus) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *VirtualMachineStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *VirtualMachineStatus) GetVolumeSnapshotStatuses() []*VirtualMachineStatus_VolumeSnapshotStatus {
	if x != nil {
		return x.VolumeSnapshotStatuses
	}
	return nil
}

type VirtualMachineList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*VirtualMachine      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineList) Reset() {
	*x = VirtualMachineList{}
	mi := &file_types_virtualmachine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineList) ProtoMessage() {}

func (x *VirtualMachineList) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineList.ProtoReflect.Descriptor instead.
func (*VirtualMachineList) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualMachineList) GetItems() []*VirtualMachine {
	if x != nil {
		return x.Items
	}
	return nil
}

type VirtualMachineHost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ips           []string               `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineHost) Reset() {
	*x = VirtualMachineHost{}
	mi := &file_types_virtualmachine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineHost) ProtoMessage() {}

func (x *VirtualMachineHost) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineHost.ProtoReflect.Descriptor instead.
func (*VirtualMachineHost) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{4}
}

func (x *VirtualMachineHost) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualMachineHost) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type DataVolumeTemplate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *ObjectMeta             `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *DataVolumeTemplateSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataVolumeTemplate) Reset() {
	*x = DataVolumeTemplate{}
	mi := &file_types_virtualmachine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataVolumeTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVolumeTemplate) ProtoMessage() {}

func (x *DataVolumeTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVolumeTemplate.ProtoReflect.Descriptor instead.
func (*DataVolumeTemplate) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{5}
}

func (x *DataVolumeTemplate) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataVolumeTemplate) GetSpec() *DataVolumeTemplateSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DataVolumeTemplateSpec struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Pvc           *DataVolumeTemplateSpec_Pvc    `protobuf:"bytes,1,opt,name=pvc,proto3" json:"pvc,omitempty"`
	Source        *DataVolumeTemplateSpec_Source `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataVolumeTemplateSpec) Reset() {
	*x = DataVolumeTemplateSpec{}
	mi := &file_types_virtualmachine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataVolumeTemplateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVolumeTemplateSpec) ProtoMessage() {}

func (x *DataVolumeTemplateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVolumeTemplateSpec.ProtoReflect.Descriptor instead.
func (*DataVolumeTemplateSpec) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{6}
}

func (x *DataVolumeTemplateSpec) GetPvc() *DataVolumeTemplateSpec_Pvc {
	if x != nil {
		return x.Pvc
	}
	return nil
}

func (x *DataVolumeTemplateSpec) GetSource() *DataVolumeTemplateSpec_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type VirtualMachineResourceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemeryUsage   float32                `protobuf:"fixed32,2,opt,name=memery_usage,json=memeryUsage,proto3" json:"memery_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineResourceMetrics) Reset() {
	*x = VirtualMachineResourceMetrics{}
	mi := &file_types_virtualmachine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineResourceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineResourceMetrics) ProtoMessage() {}

func (x *VirtualMachineResourceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineResourceMetrics.ProtoReflect.Descriptor instead.
func (*VirtualMachineResourceMetrics) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{7}
}

func (x *VirtualMachineResourceMetrics) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *VirtualMachineResourceMetrics) GetMemeryUsage() float32 {
	if x != nil {
		return x.MemeryUsage
	}
	return 0
}

type VirtualMachineNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpsName       string                 `protobuf:"bytes,2,opt,name=ips_name,json=ipsName,proto3" json:"ips_name,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Interface     string                 `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,6,opt,name=mac,proto3" json:"mac,omitempty"`
	Subnet        string                 `protobuf:"bytes,7,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Vpc           string                 `protobuf:"bytes,8,opt,name=vpc,proto3" json:"vpc,omitempty"`
	Multus        string                 `protobuf:"bytes,9,opt,name=multus,proto3" json:"multus,omitempty"`
	Default       bool                   `protobuf:"varint,10,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineNetwork) Reset() {
	*x = VirtualMachineNetwork{}
	mi := &file_types_virtualmachine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineNetwork) ProtoMessage() {}

func (x *VirtualMachineNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineNetwork.ProtoReflect.Descriptor instead.
func (*VirtualMachineNetwork) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{8}
}

func (x *VirtualMachineNetwork) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualMachineNetwork) GetIpsName() string {
	if x != nil {
		return x.IpsName
	}
	return ""
}

func (x *VirtualMachineNetwork) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *VirtualMachineNetwork) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *VirtualMachineNetwork) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *VirtualMachineNetwork) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *VirtualMachineNetwork) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *VirtualMachineNetwork) GetVpc() string {
	if x != nil {
		return x.Vpc
	}
	return ""
}

func (x *VirtualMachineNetwork) GetMultus() string {
	if x != nil {
		return x.Multus
	}
	return ""
}

func (x *VirtualMachineNetwork) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

type VirtualMachineDisk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capacity         string                 `protobuf:"bytes,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AccessMode       string                 `protobuf:"bytes,4,opt,name=accessMode,proto3" json:"accessMode,omitempty"`
	StorageClassName string                 `protobuf:"bytes,5,opt,name=storageClassName,proto3" json:"storageClassName,omitempty"`
	Rootfs           bool                   `protobuf:"varint,6,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	Mounted          bool                   `protobuf:"varint,7,opt,name=mounted,proto3" json:"mounted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VirtualMachineDisk) Reset() {
	*x = VirtualMachineDisk{}
	mi := &file_types_virtualmachine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineDisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineDisk) ProtoMessage() {}

func (x *VirtualMachineDisk) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineDisk.ProtoReflect.Descriptor instead.
func (*VirtualMachineDisk) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{9}
}

func (x *VirtualMachineDisk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualMachineDisk) GetCapacity() string {
	if x != nil {
		return x.Capacity
	}
	return ""
}

func (x *VirtualMachineDisk) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VirtualMachineDisk) GetAccessMode() string {
	if x != nil {
		return x.AccessMode
	}
	return ""
}

func (x *VirtualMachineDisk) GetStorageClassName() string {
	if x != nil {
		return x.StorageClassName
	}
	return ""
}

func (x *VirtualMachineDisk) GetRootfs() bool {
	if x != nil {
		return x.Rootfs
	}
	return false
}

func (x *VirtualMachineDisk) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

type VirtualMachineStatus_VolumeSnapshotStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineStatus_VolumeSnapshotStatus) Reset() {
	*x = VirtualMachineStatus_VolumeSnapshotStatus{}
	mi := &file_types_virtualmachine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineStatus_VolumeSnapshotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineStatus_VolumeSnapshotStatus) ProtoMessage() {}

func (x *VirtualMachineStatus_VolumeSnapshotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineStatus_VolumeSnapshotStatus.ProtoReflect.Descriptor instead.
func (*VirtualMachineStatus_VolumeSnapshotStatus) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{2, 0}
}

func (x *VirtualMachineStatus_VolumeSnapshotStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualMachineStatus_VolumeSnapshotStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *VirtualMachineStatus_VolumeSnapshotStatus) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type DataVolumeTemplateSpec_Pvc struct {
	state            protoimpl.MessageState                `protogen:"open.v1"`
	AccessModes      []string                              `protobuf:"bytes,1,rep,name=accessModes,proto3" json:"accessModes,omitempty"`
	Resources        *DataVolumeTemplateSpec_Pvc_Resources `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	StorageClassName string                                `protobuf:"bytes,3,opt,name=storageClassName,proto3" json:"storageClassName,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DataVolumeTemplateSpec_Pvc) Reset() {
	*x = DataVolumeTemplateSpec_Pvc{}
	mi := &file_types_virtualmachine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataVolumeTemplateSpec_Pvc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVolumeTemplateSpec_Pvc) ProtoMessage() {}

func (x *DataVolumeTemplateSpec_Pvc) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVolumeTemplateSpec_Pvc.ProtoReflect.Descriptor instead.
func (*DataVolumeTemplateSpec_Pvc) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DataVolumeTemplateSpec_Pvc) GetAccessModes() []string {
	if x != nil {
		return x.AccessModes
	}
	return nil
}

func (x *DataVolumeTemplateSpec_Pvc) GetResources() *DataVolumeTemplateSpec_Pvc_Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DataVolumeTemplateSpec_Pvc) GetStorageClassName() string {
	if x != nil {
		return x.StorageClassName
	}
	return ""
}

type DataVolumeTemplateSpec_Source struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Http          *DataVolumeTemplateSpec_Source_Http  `protobuf:"bytes,1,opt,name=http,proto3,oneof" json:"http,omitempty"`
	Blank         *DataVolumeTemplateSpec_Source_Blank `protobuf:"bytes,2,opt,name=blank,proto3,oneof" json:"blank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataVolumeTemplateSpec_Source) Reset() {
	*x = DataVolumeTemplateSpec_Source{}
	mi := &file_types_virtualmachine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataVolumeTemplateSpec_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVolumeTemplateSpec_Source) ProtoMessage() {}

func (x *DataVolumeTemplateSpec_Source) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVolumeTemplateSpec_Source.ProtoReflect.Descriptor instead.
func (*DataVolumeTemplateSpec_Source) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{6, 1}
}

func (x *DataVolumeTemplateSpec_Source) GetHttp() *DataVolumeTemplateSpec_Source_Http {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *DataVolumeTemplateSpec_Source) GetBlank() *DataVolumeTemplateSpec_Source_Blank {
	if x != nil {
		return x.Blank
	}
	return nil
}

type DataVolumeTemplateSpec_Pvc_Resources struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Requests      *DataVolumeTemplateSpec_Pvc_Resources_Requests `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataVolumeTemplateSpec_Pvc_Resources) Reset() {
	*x = DataVolumeTemplateSpec_Pvc_Resources{}
	mi := &file_types_virtualmachine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataVolumeTemplateSpec_Pvc_Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVolumeTemplateSpec_Pvc_Resources) ProtoMessage() {}

func (x *DataVolumeTemplateSpec_Pvc_Resources) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVolumeTemplateSpec_Pvc_Resources.ProtoReflect.Descriptor instead.
func (*DataVolumeTemplateSpec_Pvc_Resources) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *DataVolumeTemplateSpec_Pvc_Resources) GetRequests() *DataVolumeTemplateSpec_Pvc_Resources_Requests {
	if x != nil {
		return x.Requests
	}
	return nil
}

type DataVolumeTemplateSpec_Pvc_Resources_Requests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Storage       string                 `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataVolumeTemplateSpec_Pvc_Resources_Requests) Reset() {
	*x = DataVolumeTemplateSpec_Pvc_Resources_Requests{}
	mi := &file_types_virtualmachine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataVolumeTemplateSpec_Pvc_Resources_Requests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVolumeTemplateSpec_Pvc_Resources_Requests) ProtoMessage() {}

func (x *DataVolumeTemplateSpec_Pvc_Resources_Requests) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVolumeTemplateSpec_Pvc_Resources_Requests.ProtoReflect.Descriptor instead.
func (*DataVolumeTemplateSpec_Pvc_Resources_Requests) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{6, 0, 0, 0}
}

func (x *DataVolumeTemplateSpec_Pvc_Resources_Requests) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

type DataVolumeTemplateSpec_Source_Http struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataVolumeTemplateSpec_Source_Http) Reset() {
	*x = DataVolumeTemplateSpec_Source_Http{}
	mi := &file_types_virtualmachine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataVolumeTemplateSpec_Source_Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVolumeTemplateSpec_Source_Http) ProtoMessage() {}

func (x *DataVolumeTemplateSpec_Source_Http) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVolumeTemplateSpec_Source_Http.ProtoReflect.Descriptor instead.
func (*DataVolumeTemplateSpec_Source_Http) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{6, 1, 0}
}

func (x *DataVolumeTemplateSpec_Source_Http) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DataVolumeTemplateSpec_Source_Blank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataVolumeTemplateSpec_Source_Blank) Reset() {
	*x = DataVolumeTemplateSpec_Source_Blank{}
	mi := &file_types_virtualmachine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataVolumeTemplateSpec_Source_Blank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVolumeTemplateSpec_Source_Blank) ProtoMessage() {}

func (x *DataVolumeTemplateSpec_Source_Blank) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVolumeTemplateSpec_Source_Blank.ProtoReflect.Descriptor instead.
func (*DataVolumeTemplateSpec_Source_Blank) Descriptor() ([]byte, []int) {
	return file_types_virtualmachine_proto_rawDescGZIP(), []int{6, 1, 1}
}

var File_types_virtualmachine_proto protoreflect.FileDescriptor

const file_types_virtualmachine_proto_rawDesc = "" +
	"\n" +
	"\x1atypes/virtualmachine.proto\x12\x19vink.kubevm.io.apis.types\x1a\"types/virtualmachineinstance.proto\x1a\x14types/metadata.proto\x1a\x11types/types.proto\"\x93\x02\n" +
	"\x0eVirtualMachine\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12A\n" +
	"\bmetadata\x18\x03 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12A\n" +
	"\x04spec\x18\x04 \x01(\v2-.vink.kubevm.io.apis.types.VirtualMachineSpecR\x04spec\x12G\n" +
	"\x06status\x18\x05 \x01(\v2/.vink.kubevm.io.apis.types.VirtualMachineStatusR\x06status\"\xf2\x01\n" +
	"\x12VirtualMachineSpec\x12 \n" +
	"\vrunStrategy\x18\x01 \x01(\tR\vrunStrategy\x12Y\n" +
	"\btemplate\x18\x02 \x01(\v2=.vink.kubevm.io.apis.types.VirtualMachineInstanceTemplateSpecR\btemplate\x12_\n" +
	"\x13dataVolumeTemplates\x18\x03 \x03(\v2-.vink.kubevm.io.apis.types.DataVolumeTemplateR\x13dataVolumeTemplates\"\xc4\x03\n" +
	"\x14VirtualMachineStatus\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12(\n" +
	"\x0fprintableStatus\x18\x02 \x01(\tR\x0fprintableStatus\x12 \n" +
	"\vrunStrategy\x18\x03 \x01(\tR\vrunStrategy\x12\x18\n" +
	"\acreated\x18\x04 \x01(\bR\acreated\x12D\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2$.vink.kubevm.io.apis.types.ConditionR\n" +
	"conditions\x12|\n" +
	"\x16volumeSnapshotStatuses\x18\x06 \x03(\v2D.vink.kubevm.io.apis.types.VirtualMachineStatus.VolumeSnapshotStatusR\x16volumeSnapshotStatuses\x1al\n" +
	"\x14VolumeSnapshotStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"U\n" +
	"\x12VirtualMachineList\x12?\n" +
	"\x05items\x18\x01 \x03(\v2).vink.kubevm.io.apis.types.VirtualMachineR\x05items\":\n" +
	"\x12VirtualMachineHost\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\"\x9e\x01\n" +
	"\x12DataVolumeTemplate\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12E\n" +
	"\x04spec\x18\x02 \x01(\v21.vink.kubevm.io.apis.types.DataVolumeTemplateSpecR\x04spec\"\xf6\x05\n" +
	"\x16DataVolumeTemplateSpec\x12G\n" +
	"\x03pvc\x18\x01 \x01(\v25.vink.kubevm.io.apis.types.DataVolumeTemplateSpec.PvcR\x03pvc\x12P\n" +
	"\x06source\x18\x02 \x01(\v28.vink.kubevm.io.apis.types.DataVolumeTemplateSpec.SourceR\x06source\x1a\xcc\x02\n" +
	"\x03Pvc\x12 \n" +
	"\vaccessModes\x18\x01 \x03(\tR\vaccessModes\x12]\n" +
	"\tresources\x18\x02 \x01(\v2?.vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc.ResourcesR\tresources\x12*\n" +
	"\x10storageClassName\x18\x03 \x01(\tR\x10storageClassName\x1a\x97\x01\n" +
	"\tResources\x12d\n" +
	"\brequests\x18\x01 \x01(\v2H.vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc.Resources.RequestsR\brequests\x1a$\n" +
	"\bRequests\x12\x18\n" +
	"\astorage\x18\x01 \x01(\tR\astorage\x1a\xf1\x01\n" +
	"\x06Source\x12V\n" +
	"\x04http\x18\x01 \x01(\v2=.vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source.HttpH\x00R\x04http\x88\x01\x01\x12Y\n" +
	"\x05blank\x18\x02 \x01(\v2>.vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source.BlankH\x01R\x05blank\x88\x01\x01\x1a\x18\n" +
	"\x04Http\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x1a\a\n" +
	"\x05BlankB\a\n" +
	"\x05_httpB\b\n" +
	"\x06_blank\"_\n" +
	"\x1dVirtualMachineResourceMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemery_usage\x18\x02 \x01(\x02R\vmemeryUsage\"\xfc\x01\n" +
	"\x15VirtualMachineNetwork\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bips_name\x18\x02 \x01(\tR\aipsName\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterface\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x06 \x01(\tR\x03mac\x12\x16\n" +
	"\x06subnet\x18\a \x01(\tR\x06subnet\x12\x10\n" +
	"\x03vpc\x18\b \x01(\tR\x03vpc\x12\x16\n" +
	"\x06multus\x18\t \x01(\tR\x06multus\x12\x18\n" +
	"\adefault\x18\n" +
	" \x01(\bR\adefault\"\xda\x01\n" +
	"\x12VirtualMachineDisk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\tR\bcapacity\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"accessMode\x18\x04 \x01(\tR\n" +
	"accessMode\x12*\n" +
	"\x10storageClassName\x18\x05 \x01(\tR\x10storageClassName\x12\x16\n" +
	"\x06rootfs\x18\x06 \x01(\bR\x06rootfs\x12\x18\n" +
	"\amounted\x18\a \x01(\bR\amountedB&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_virtualmachine_proto_rawDescOnce sync.Once
	file_types_virtualmachine_proto_rawDescData []byte
)

func file_types_virtualmachine_proto_rawDescGZIP() []byte {
	file_types_virtualmachine_proto_rawDescOnce.Do(func() {
		file_types_virtualmachine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_virtualmachine_proto_rawDesc), len(file_types_virtualmachine_proto_rawDesc)))
	})
	return file_types_virtualmachine_proto_rawDescData
}

var file_types_virtualmachine_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_types_virtualmachine_proto_goTypes = []any{
	(*VirtualMachine)(nil),                                // 0: vink.kubevm.io.apis.types.VirtualMachine
	(*VirtualMachineSpec)(nil),                            // 1: vink.kubevm.io.apis.types.VirtualMachineSpec
	(*VirtualMachineStatus)(nil),                          // 2: vink.kubevm.io.apis.types.VirtualMachineStatus
	(*VirtualMachineList)(nil),                            // 3: vink.kubevm.io.apis.types.VirtualMachineList
	(*VirtualMachineHost)(nil),                            // 4: vink.kubevm.io.apis.types.VirtualMachineHost
	(*DataVolumeTemplate)(nil),                            // 5: vink.kubevm.io.apis.types.DataVolumeTemplate
	(*DataVolumeTemplateSpec)(nil),                        // 6: vink.kubevm.io.apis.types.DataVolumeTemplateSpec
	(*VirtualMachineResourceMetrics)(nil),                 // 7: vink.kubevm.io.apis.types.VirtualMachineResourceMetrics
	(*VirtualMachineNetwork)(nil),                         // 8: vink.kubevm.io.apis.types.VirtualMachineNetwork
	(*VirtualMachineDisk)(nil),                            // 9: vink.kubevm.io.apis.types.VirtualMachineDisk
	(*VirtualMachineStatus_VolumeSnapshotStatus)(nil),     // 10: vink.kubevm.io.apis.types.VirtualMachineStatus.VolumeSnapshotStatus
	(*DataVolumeTemplateSpec_Pvc)(nil),                    // 11: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc
	(*DataVolumeTemplateSpec_Source)(nil),                 // 12: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source
	(*DataVolumeTemplateSpec_Pvc_Resources)(nil),          // 13: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc.Resources
	(*DataVolumeTemplateSpec_Pvc_Resources_Requests)(nil), // 14: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc.Resources.Requests
	(*DataVolumeTemplateSpec_Source_Http)(nil),            // 15: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source.Http
	(*DataVolumeTemplateSpec_Source_Blank)(nil),           // 16: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source.Blank
	(*ObjectMeta)(nil),                                    // 17: vink.kubevm.io.apis.types.ObjectMeta
	(*VirtualMachineInstanceTemplateSpec)(nil),            // 18: vink.kubevm.io.apis.types.VirtualMachineInstanceTemplateSpec
	(*Condition)(nil),                                     // 19: vink.kubevm.io.apis.types.Condition
}
var file_types_virtualmachine_proto_depIdxs = []int32{
	17, // 0: vink.kubevm.io.apis.types.VirtualMachine.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	1,  // 1: vink.kubevm.io.apis.types.VirtualMachine.spec:type_name -> vink.kubevm.io.apis.types.VirtualMachineSpec
	2,  // 2: vink.kubevm.io.apis.types.VirtualMachine.status:type_name -> vink.kubevm.io.apis.types.VirtualMachineStatus
	18, // 3: vink.kubevm.io.apis.types.VirtualMachineSpec.template:type_name -> vink.kubevm.io.apis.types.VirtualMachineInstanceTemplateSpec
	5,  // 4: vink.kubevm.io.apis.types.VirtualMachineSpec.dataVolumeTemplates:type_name -> vink.kubevm.io.apis.types.DataVolumeTemplate
	19, // 5: vink.kubevm.io.apis.types.VirtualMachineStatus.conditions:type_name -> vink.kubevm.io.apis.types.Condition
	10, // 6: vink.kubevm.io.apis.types.VirtualMachineStatus.volumeSnapshotStatuses:type_name -> vink.kubevm.io.apis.types.VirtualMachineStatus.VolumeSnapshotStatus
	0,  // 7: vink.kubevm.io.apis.types.VirtualMachineList.items:type_name -> vink.kubevm.io.apis.types.VirtualMachine
	17, // 8: vink.kubevm.io.apis.types.DataVolumeTemplate.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	6,  // 9: vink.kubevm.io.apis.types.DataVolumeTemplate.spec:type_name -> vink.kubevm.io.apis.types.DataVolumeTemplateSpec
	11, // 10: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.pvc:type_name -> vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc
	12, // 11: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.source:type_name -> vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source
	13, // 12: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc.resources:type_name -> vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc.Resources
	15, // 13: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source.http:type_name -> vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source.Http
	16, // 14: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source.blank:type_name -> vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Source.Blank
	14, // 15: vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc.Resources.requests:type_name -> vink.kubevm.io.apis.types.DataVolumeTemplateSpec.Pvc.Resources.Requests
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_types_virtualmachine_proto_init() }
func file_types_virtualmachine_proto_init() {
	if File_types_virtualmachine_proto != nil {
		return
	}
	file_types_virtualmachineinstance_proto_init()
	file_types_metadata_proto_init()
	file_types_types_proto_init()
	file_types_virtualmachine_proto_msgTypes[10].OneofWrappers = []any{}
	file_types_virtualmachine_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_virtualmachine_proto_rawDesc), len(file_types_virtualmachine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_virtualmachine_proto_goTypes,
		DependencyIndexes: file_types_virtualmachine_proto_depIdxs,
		MessageInfos:      file_types_virtualmachine_proto_msgTypes,
	}.Build()
	File_types_virtualmachine_proto = out.File
	file_types_virtualmachine_proto_goTypes = nil
	file_types_virtualmachine_proto_depIdxs = nil
}
