// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using VirtualMachineRestore within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineRestore) DeepCopyInto(out *VirtualMachineRestore) {
	p := proto.Clone(in).(*VirtualMachineRestore)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestore. Required by controller-gen.
func (in *VirtualMachineRestore) DeepCopy() *VirtualMachineRestore {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestore. Required by controller-gen.
func (in *VirtualMachineRestore) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineRestoreList within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineRestoreList) DeepCopyInto(out *VirtualMachineRestoreList) {
	p := proto.Clone(in).(*VirtualMachineRestoreList)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreList. Required by controller-gen.
func (in *VirtualMachineRestoreList) DeepCopy() *VirtualMachineRestoreList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreList. Required by controller-gen.
func (in *VirtualMachineRestoreList) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineRestoreSpec within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineRestoreSpec) DeepCopyInto(out *VirtualMachineRestoreSpec) {
	p := proto.Clone(in).(*VirtualMachineRestoreSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreSpec. Required by controller-gen.
func (in *VirtualMachineRestoreSpec) DeepCopy() *VirtualMachineRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreSpec. Required by controller-gen.
func (in *VirtualMachineRestoreSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineRestoreSpec_Reference within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineRestoreSpec_Reference) DeepCopyInto(out *VirtualMachineRestoreSpec_Reference) {
	p := proto.Clone(in).(*VirtualMachineRestoreSpec_Reference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreSpec_Reference. Required by controller-gen.
func (in *VirtualMachineRestoreSpec_Reference) DeepCopy() *VirtualMachineRestoreSpec_Reference {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreSpec_Reference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreSpec_Reference. Required by controller-gen.
func (in *VirtualMachineRestoreSpec_Reference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineRestoreStatus within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineRestoreStatus) DeepCopyInto(out *VirtualMachineRestoreStatus) {
	p := proto.Clone(in).(*VirtualMachineRestoreStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreStatus. Required by controller-gen.
func (in *VirtualMachineRestoreStatus) DeepCopy() *VirtualMachineRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreStatus. Required by controller-gen.
func (in *VirtualMachineRestoreStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
