// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/virtualmachinerestore.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualMachineRestore struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Kind          string                       `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion    string                       `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Metadata      *ObjectMeta                  `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *VirtualMachineRestoreSpec   `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VirtualMachineRestoreStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineRestore) Reset() {
	*x = VirtualMachineRestore{}
	mi := &file_types_virtualmachinerestore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineRestore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineRestore) ProtoMessage() {}

func (x *VirtualMachineRestore) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinerestore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineRestore.ProtoReflect.Descriptor instead.
func (*VirtualMachineRestore) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinerestore_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachineRestore) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VirtualMachineRestore) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *VirtualMachineRestore) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VirtualMachineRestore) GetSpec() *VirtualMachineRestoreSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *VirtualMachineRestore) GetStatus() *VirtualMachineRestoreStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type VirtualMachineRestoreList struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*VirtualMachineRestore `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineRestoreList) Reset() {
	*x = VirtualMachineRestoreList{}
	mi := &file_types_virtualmachinerestore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineRestoreList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineRestoreList) ProtoMessage() {}

func (x *VirtualMachineRestoreList) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinerestore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineRestoreList.ProtoReflect.Descriptor instead.
func (*VirtualMachineRestoreList) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinerestore_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualMachineRestoreList) GetItems() []*VirtualMachineRestore {
	if x != nil {
		return x.Items
	}
	return nil
}

type VirtualMachineRestoreSpec struct {
	state                      protoimpl.MessageState               `protogen:"open.v1"`
	Target                     *VirtualMachineRestoreSpec_Reference `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	VirtualMachineSnapshotName string                               `protobuf:"bytes,2,opt,name=virtualMachineSnapshotName,proto3" json:"virtualMachineSnapshotName,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *VirtualMachineRestoreSpec) Reset() {
	*x = VirtualMachineRestoreSpec{}
	mi := &file_types_virtualmachinerestore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineRestoreSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineRestoreSpec) ProtoMessage() {}

func (x *VirtualMachineRestoreSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinerestore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineRestoreSpec.ProtoReflect.Descriptor instead.
func (*VirtualMachineRestoreSpec) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinerestore_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualMachineRestoreSpec) GetTarget() *VirtualMachineRestoreSpec_Reference {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *VirtualMachineRestoreSpec) GetVirtualMachineSnapshotName() string {
	if x != nil {
		return x.VirtualMachineSnapshotName
	}
	return ""
}

type VirtualMachineRestoreStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Complete      bool                   `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	RestoreTime   string                 `protobuf:"bytes,2,opt,name=restoreTime,proto3" json:"restoreTime,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineRestoreStatus) Reset() {
	*x = VirtualMachineRestoreStatus{}
	mi := &file_types_virtualmachinerestore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineRestoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineRestoreStatus) ProtoMessage() {}

func (x *VirtualMachineRestoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinerestore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineRestoreStatus.ProtoReflect.Descriptor instead.
func (*VirtualMachineRestoreStatus) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinerestore_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualMachineRestoreStatus) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *VirtualMachineRestoreStatus) GetRestoreTime() string {
	if x != nil {
		return x.RestoreTime
	}
	return ""
}

func (x *VirtualMachineRestoreStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type VirtualMachineRestoreSpec_Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiGroup      string                 `protobuf:"bytes,1,opt,name=apiGroup,proto3" json:"apiGroup,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineRestoreSpec_Reference) Reset() {
	*x = VirtualMachineRestoreSpec_Reference{}
	mi := &file_types_virtualmachinerestore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineRestoreSpec_Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineRestoreSpec_Reference) ProtoMessage() {}

func (x *VirtualMachineRestoreSpec_Reference) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinerestore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineRestoreSpec_Reference.ProtoReflect.Descriptor instead.
func (*VirtualMachineRestoreSpec_Reference) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinerestore_proto_rawDescGZIP(), []int{2, 0}
}

func (x *VirtualMachineRestoreSpec_Reference) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *VirtualMachineRestoreSpec_Reference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VirtualMachineRestoreSpec_Reference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_types_virtualmachinerestore_proto protoreflect.FileDescriptor

const file_types_virtualmachinerestore_proto_rawDesc = "" +
	"\n" +
	"!types/virtualmachinerestore.proto\x12\x19vink.kubevm.io.apis.types\x1a\x14types/metadata.proto\x1a\x11types/types.proto\"\xa8\x02\n" +
	"\x15VirtualMachineRestore\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12A\n" +
	"\bmetadata\x18\x03 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12H\n" +
	"\x04spec\x18\x04 \x01(\v24.vink.kubevm.io.apis.types.VirtualMachineRestoreSpecR\x04spec\x12N\n" +
	"\x06status\x18\x05 \x01(\v26.vink.kubevm.io.apis.types.VirtualMachineRestoreStatusR\x06status\"c\n" +
	"\x19VirtualMachineRestoreList\x12F\n" +
	"\x05items\x18\x01 \x03(\v20.vink.kubevm.io.apis.types.VirtualMachineRestoreR\x05items\"\x84\x02\n" +
	"\x19VirtualMachineRestoreSpec\x12V\n" +
	"\x06target\x18\x01 \x01(\v2>.vink.kubevm.io.apis.types.VirtualMachineRestoreSpec.ReferenceR\x06target\x12>\n" +
	"\x1avirtualMachineSnapshotName\x18\x02 \x01(\tR\x1avirtualMachineSnapshotName\x1aO\n" +
	"\tReference\x12\x1a\n" +
	"\bapiGroup\x18\x01 \x01(\tR\bapiGroup\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xa1\x01\n" +
	"\x1bVirtualMachineRestoreStatus\x12\x1a\n" +
	"\bcomplete\x18\x01 \x01(\bR\bcomplete\x12 \n" +
	"\vrestoreTime\x18\x02 \x01(\tR\vrestoreTime\x12D\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2$.vink.kubevm.io.apis.types.ConditionR\n" +
	"conditionsB&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_virtualmachinerestore_proto_rawDescOnce sync.Once
	file_types_virtualmachinerestore_proto_rawDescData []byte
)

func file_types_virtualmachinerestore_proto_rawDescGZIP() []byte {
	file_types_virtualmachinerestore_proto_rawDescOnce.Do(func() {
		file_types_virtualmachinerestore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_virtualmachinerestore_proto_rawDesc), len(file_types_virtualmachinerestore_proto_rawDesc)))
	})
	return file_types_virtualmachinerestore_proto_rawDescData
}

var file_types_virtualmachinerestore_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_types_virtualmachinerestore_proto_goTypes = []any{
	(*VirtualMachineRestore)(nil),               // 0: vink.kubevm.io.apis.types.VirtualMachineRestore
	(*VirtualMachineRestoreList)(nil),           // 1: vink.kubevm.io.apis.types.VirtualMachineRestoreList
	(*VirtualMachineRestoreSpec)(nil),           // 2: vink.kubevm.io.apis.types.VirtualMachineRestoreSpec
	(*VirtualMachineRestoreStatus)(nil),         // 3: vink.kubevm.io.apis.types.VirtualMachineRestoreStatus
	(*VirtualMachineRestoreSpec_Reference)(nil), // 4: vink.kubevm.io.apis.types.VirtualMachineRestoreSpec.Reference
	(*ObjectMeta)(nil),                          // 5: vink.kubevm.io.apis.types.ObjectMeta
	(*Condition)(nil),                           // 6: vink.kubevm.io.apis.types.Condition
}
var file_types_virtualmachinerestore_proto_depIdxs = []int32{
	5, // 0: vink.kubevm.io.apis.types.VirtualMachineRestore.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	2, // 1: vink.kubevm.io.apis.types.VirtualMachineRestore.spec:type_name -> vink.kubevm.io.apis.types.VirtualMachineRestoreSpec
	3, // 2: vink.kubevm.io.apis.types.VirtualMachineRestore.status:type_name -> vink.kubevm.io.apis.types.VirtualMachineRestoreStatus
	0, // 3: vink.kubevm.io.apis.types.VirtualMachineRestoreList.items:type_name -> vink.kubevm.io.apis.types.VirtualMachineRestore
	4, // 4: vink.kubevm.io.apis.types.VirtualMachineRestoreSpec.target:type_name -> vink.kubevm.io.apis.types.VirtualMachineRestoreSpec.Reference
	6, // 5: vink.kubevm.io.apis.types.VirtualMachineRestoreStatus.conditions:type_name -> vink.kubevm.io.apis.types.Condition
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_types_virtualmachinerestore_proto_init() }
func file_types_virtualmachinerestore_proto_init() {
	if File_types_virtualmachinerestore_proto != nil {
		return
	}
	file_types_metadata_proto_init()
	file_types_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_virtualmachinerestore_proto_rawDesc), len(file_types_virtualmachinerestore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_virtualmachinerestore_proto_goTypes,
		DependencyIndexes: file_types_virtualmachinerestore_proto_depIdxs,
		MessageInfos:      file_types_virtualmachinerestore_proto_msgTypes,
	}.Build()
	File_types_virtualmachinerestore_proto = out.File
	file_types_virtualmachinerestore_proto_goTypes = nil
	file_types_virtualmachinerestore_proto_depIdxs = nil
}
