// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/virtualmachineclone.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualMachineClone struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Kind          string                     `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion    string                     `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Metadata      *ObjectMeta                `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *VirtualMachineCloneSpec   `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VirtualMachineCloneStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineClone) Reset() {
	*x = VirtualMachineClone{}
	mi := &file_types_virtualmachineclone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineClone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineClone) ProtoMessage() {}

func (x *VirtualMachineClone) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineclone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineClone.ProtoReflect.Descriptor instead.
func (*VirtualMachineClone) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineclone_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachineClone) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VirtualMachineClone) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *VirtualMachineClone) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VirtualMachineClone) GetSpec() *VirtualMachineCloneSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *VirtualMachineClone) GetStatus() *VirtualMachineCloneStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type VirtualMachineCloneList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*VirtualMachineClone `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineCloneList) Reset() {
	*x = VirtualMachineCloneList{}
	mi := &file_types_virtualmachineclone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineCloneList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineCloneList) ProtoMessage() {}

func (x *VirtualMachineCloneList) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineclone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineCloneList.ProtoReflect.Descriptor instead.
func (*VirtualMachineCloneList) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineclone_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualMachineCloneList) GetItems() []*VirtualMachineClone {
	if x != nil {
		return x.Items
	}
	return nil
}

type VirtualMachineCloneSpec struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Source        *VirtualMachineCloneSpec_Reference `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        *VirtualMachineCloneSpec_Reference `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineCloneSpec) Reset() {
	*x = VirtualMachineCloneSpec{}
	mi := &file_types_virtualmachineclone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineCloneSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineCloneSpec) ProtoMessage() {}

func (x *VirtualMachineCloneSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineclone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineCloneSpec.ProtoReflect.Descriptor instead.
func (*VirtualMachineCloneSpec) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineclone_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualMachineCloneSpec) GetSource() *VirtualMachineCloneSpec_Reference {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *VirtualMachineCloneSpec) GetTarget() *VirtualMachineCloneSpec_Reference {
	if x != nil {
		return x.Target
	}
	return nil
}

type VirtualMachineCloneStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	TargetName    string                 `protobuf:"bytes,2,opt,name=targetName,proto3" json:"targetName,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineCloneStatus) Reset() {
	*x = VirtualMachineCloneStatus{}
	mi := &file_types_virtualmachineclone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineCloneStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineCloneStatus) ProtoMessage() {}

func (x *VirtualMachineCloneStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineclone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineCloneStatus.ProtoReflect.Descriptor instead.
func (*VirtualMachineCloneStatus) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineclone_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualMachineCloneStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *VirtualMachineCloneStatus) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *VirtualMachineCloneStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type VirtualMachineCloneSpec_Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiGroup      string                 `protobuf:"bytes,1,opt,name=apiGroup,proto3" json:"apiGroup,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineCloneSpec_Reference) Reset() {
	*x = VirtualMachineCloneSpec_Reference{}
	mi := &file_types_virtualmachineclone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineCloneSpec_Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineCloneSpec_Reference) ProtoMessage() {}

func (x *VirtualMachineCloneSpec_Reference) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineclone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineCloneSpec_Reference.ProtoReflect.Descriptor instead.
func (*VirtualMachineCloneSpec_Reference) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineclone_proto_rawDescGZIP(), []int{2, 0}
}

func (x *VirtualMachineCloneSpec_Reference) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *VirtualMachineCloneSpec_Reference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VirtualMachineCloneSpec_Reference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_types_virtualmachineclone_proto protoreflect.FileDescriptor

const file_types_virtualmachineclone_proto_rawDesc = "" +
	"\n" +
	"\x1ftypes/virtualmachineclone.proto\x12\x19vink.kubevm.io.apis.types\x1a\x14types/metadata.proto\x1a\x11types/types.proto\"\xa2\x02\n" +
	"\x13VirtualMachineClone\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12A\n" +
	"\bmetadata\x18\x03 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12F\n" +
	"\x04spec\x18\x04 \x01(\v22.vink.kubevm.io.apis.types.VirtualMachineCloneSpecR\x04spec\x12L\n" +
	"\x06status\x18\x05 \x01(\v24.vink.kubevm.io.apis.types.VirtualMachineCloneStatusR\x06status\"_\n" +
	"\x17VirtualMachineCloneList\x12D\n" +
	"\x05items\x18\x01 \x03(\v2..vink.kubevm.io.apis.types.VirtualMachineCloneR\x05items\"\x96\x02\n" +
	"\x17VirtualMachineCloneSpec\x12T\n" +
	"\x06source\x18\x01 \x01(\v2<.vink.kubevm.io.apis.types.VirtualMachineCloneSpec.ReferenceR\x06source\x12T\n" +
	"\x06target\x18\x02 \x01(\v2<.vink.kubevm.io.apis.types.VirtualMachineCloneSpec.ReferenceR\x06target\x1aO\n" +
	"\tReference\x12\x1a\n" +
	"\bapiGroup\x18\x01 \x01(\tR\bapiGroup\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x97\x01\n" +
	"\x19VirtualMachineCloneStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1e\n" +
	"\n" +
	"targetName\x18\x02 \x01(\tR\n" +
	"targetName\x12D\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2$.vink.kubevm.io.apis.types.ConditionR\n" +
	"conditionsB&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_virtualmachineclone_proto_rawDescOnce sync.Once
	file_types_virtualmachineclone_proto_rawDescData []byte
)

func file_types_virtualmachineclone_proto_rawDescGZIP() []byte {
	file_types_virtualmachineclone_proto_rawDescOnce.Do(func() {
		file_types_virtualmachineclone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_virtualmachineclone_proto_rawDesc), len(file_types_virtualmachineclone_proto_rawDesc)))
	})
	return file_types_virtualmachineclone_proto_rawDescData
}

var file_types_virtualmachineclone_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_types_virtualmachineclone_proto_goTypes = []any{
	(*VirtualMachineClone)(nil),               // 0: vink.kubevm.io.apis.types.VirtualMachineClone
	(*VirtualMachineCloneList)(nil),           // 1: vink.kubevm.io.apis.types.VirtualMachineCloneList
	(*VirtualMachineCloneSpec)(nil),           // 2: vink.kubevm.io.apis.types.VirtualMachineCloneSpec
	(*VirtualMachineCloneStatus)(nil),         // 3: vink.kubevm.io.apis.types.VirtualMachineCloneStatus
	(*VirtualMachineCloneSpec_Reference)(nil), // 4: vink.kubevm.io.apis.types.VirtualMachineCloneSpec.Reference
	(*ObjectMeta)(nil),                        // 5: vink.kubevm.io.apis.types.ObjectMeta
	(*Condition)(nil),                         // 6: vink.kubevm.io.apis.types.Condition
}
var file_types_virtualmachineclone_proto_depIdxs = []int32{
	5, // 0: vink.kubevm.io.apis.types.VirtualMachineClone.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	2, // 1: vink.kubevm.io.apis.types.VirtualMachineClone.spec:type_name -> vink.kubevm.io.apis.types.VirtualMachineCloneSpec
	3, // 2: vink.kubevm.io.apis.types.VirtualMachineClone.status:type_name -> vink.kubevm.io.apis.types.VirtualMachineCloneStatus
	0, // 3: vink.kubevm.io.apis.types.VirtualMachineCloneList.items:type_name -> vink.kubevm.io.apis.types.VirtualMachineClone
	4, // 4: vink.kubevm.io.apis.types.VirtualMachineCloneSpec.source:type_name -> vink.kubevm.io.apis.types.VirtualMachineCloneSpec.Reference
	4, // 5: vink.kubevm.io.apis.types.VirtualMachineCloneSpec.target:type_name -> vink.kubevm.io.apis.types.VirtualMachineCloneSpec.Reference
	6, // 6: vink.kubevm.io.apis.types.VirtualMachineCloneStatus.conditions:type_name -> vink.kubevm.io.apis.types.Condition
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_types_virtualmachineclone_proto_init() }
func file_types_virtualmachineclone_proto_init() {
	if File_types_virtualmachineclone_proto != nil {
		return
	}
	file_types_metadata_proto_init()
	file_types_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_virtualmachineclone_proto_rawDesc), len(file_types_virtualmachineclone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_virtualmachineclone_proto_goTypes,
		DependencyIndexes: file_types_virtualmachineclone_proto_depIdxs,
		MessageInfos:      file_types_virtualmachineclone_proto_msgTypes,
	}.Build()
	File_types_virtualmachineclone_proto = out.File
	file_types_virtualmachineclone_proto_goTypes = nil
	file_types_virtualmachineclone_proto_depIdxs = nil
}
