// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/virtualmachineinstance.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualMachineInstance struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Kind          string                        `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion    string                        `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Metadata      *ObjectMeta                   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *VirtualMachineInstanceSpec   `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VirtualMachineInstanceStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineInstance) Reset() {
	*x = VirtualMachineInstance{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineInstance) ProtoMessage() {}

func (x *VirtualMachineInstance) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineInstance.ProtoReflect.Descriptor instead.
func (*VirtualMachineInstance) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachineInstance) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VirtualMachineInstance) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *VirtualMachineInstance) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VirtualMachineInstance) GetSpec() *VirtualMachineInstanceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *VirtualMachineInstance) GetStatus() *VirtualMachineInstanceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type VirtualMachineInstanceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Architecture  string                 `protobuf:"bytes,1,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Domain        *DomainSpec            `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Networks      []*Network             `protobuf:"bytes,3,rep,name=networks,proto3" json:"networks,omitempty"`
	Volumes       []*Volume              `protobuf:"bytes,4,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineInstanceSpec) Reset() {
	*x = VirtualMachineInstanceSpec{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineInstanceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineInstanceSpec) ProtoMessage() {}

func (x *VirtualMachineInstanceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineInstanceSpec.ProtoReflect.Descriptor instead.
func (*VirtualMachineInstanceSpec) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualMachineInstanceSpec) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *VirtualMachineInstanceSpec) GetDomain() *DomainSpec {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *VirtualMachineInstanceSpec) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *VirtualMachineInstanceSpec) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type DomainSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *Cpu                   `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *Memory                `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Resources     *Resources             `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Devices       *Devices               `protobuf:"bytes,4,opt,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainSpec) Reset() {
	*x = DomainSpec{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainSpec) ProtoMessage() {}

func (x *DomainSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainSpec.ProtoReflect.Descriptor instead.
func (*DomainSpec) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{2}
}

func (x *DomainSpec) GetCpu() *Cpu {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *DomainSpec) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *DomainSpec) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DomainSpec) GetDevices() *Devices {
	if x != nil {
		return x.Devices
	}
	return nil
}

type Cpu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cores         uint32                 `protobuf:"varint,1,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads       uint32                 `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	Model         *string                `protobuf:"bytes,3,opt,name=model,proto3,oneof" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cpu) Reset() {
	*x = Cpu{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpu) ProtoMessage() {}

func (x *Cpu) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpu.ProtoReflect.Descriptor instead.
func (*Cpu) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{3}
}

func (x *Cpu) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *Cpu) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *Cpu) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

type Memory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guest         string                 `protobuf:"bytes,1,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{4}
}

func (x *Memory) GetGuest() string {
	if x != nil {
		return x.Guest
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      *Requests              `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Limits        *Requests              `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{5}
}

func (x *Resources) GetRequests() *Requests {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *Resources) GetLimits() *Requests {
	if x != nil {
		return x.Limits
	}
	return nil
}

type Requests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        string                 `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu           string                 `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requests) Reset() {
	*x = Requests{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requests) ProtoMessage() {}

func (x *Requests) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requests.ProtoReflect.Descriptor instead.
func (*Requests) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{6}
}

func (x *Requests) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Requests) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

type Devices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*Disk                `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	Interfaces    []*Interface           `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Devices) Reset() {
	*x = Devices{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Devices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devices) ProtoMessage() {}

func (x *Devices) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devices.ProtoReflect.Descriptor instead.
func (*Devices) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{7}
}

func (x *Devices) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Devices) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BootOrder     *int32                 `protobuf:"varint,2,opt,name=bootOrder,proto3,oneof" json:"bootOrder,omitempty"`
	Disk          *Disk_Disk             `protobuf:"bytes,3,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{8}
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disk) GetBootOrder() int32 {
	if x != nil && x.BootOrder != nil {
		return *x.BootOrder
	}
	return 0
}

func (x *Disk) GetDisk() *Disk_Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bridge        *emptypb.Empty         `protobuf:"bytes,2,opt,name=bridge,proto3,oneof" json:"bridge,omitempty"`
	Masquerade    *emptypb.Empty         `protobuf:"bytes,3,opt,name=masquerade,proto3,oneof" json:"masquerade,omitempty"`
	Sriov         *emptypb.Empty         `protobuf:"bytes,4,opt,name=sriov,proto3,oneof" json:"sriov,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{9}
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interface) GetBridge() *emptypb.Empty {
	if x != nil {
		return x.Bridge
	}
	return nil
}

func (x *Interface) GetMasquerade() *emptypb.Empty {
	if x != nil {
		return x.Masquerade
	}
	return nil
}

func (x *Interface) GetSriov() *emptypb.Empty {
	if x != nil {
		return x.Sriov
	}
	return nil
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Multus        *Network_Multus        `protobuf:"bytes,2,opt,name=multus,proto3,oneof" json:"multus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{10}
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetMultus() *Network_Multus {
	if x != nil {
		return x.Multus
	}
	return nil
}

type Volume struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Name             string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataVolume       *Volume_DataVolume       `protobuf:"bytes,2,opt,name=dataVolume,proto3,oneof" json:"dataVolume,omitempty"`
	CloudInitNoCloud *Volume_CloudInitNoCloud `protobuf:"bytes,3,opt,name=cloudInitNoCloud,proto3,oneof" json:"cloudInitNoCloud,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{11}
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetDataVolume() *Volume_DataVolume {
	if x != nil {
		return x.DataVolume
	}
	return nil
}

func (x *Volume) GetCloudInitNoCloud() *Volume_CloudInitNoCloud {
	if x != nil {
		return x.CloudInitNoCloud
	}
	return nil
}

type VirtualMachineInstanceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineInstanceStatus) Reset() {
	*x = VirtualMachineInstanceStatus{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineInstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineInstanceStatus) ProtoMessage() {}

func (x *VirtualMachineInstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineInstanceStatus.ProtoReflect.Descriptor instead.
func (*VirtualMachineInstanceStatus) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{12}
}

type VirtualMachineInstanceList struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*VirtualMachineInstance `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineInstanceList) Reset() {
	*x = VirtualMachineInstanceList{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineInstanceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineInstanceList) ProtoMessage() {}

func (x *VirtualMachineInstanceList) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineInstanceList.ProtoReflect.Descriptor instead.
func (*VirtualMachineInstanceList) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{13}
}

func (x *VirtualMachineInstanceList) GetItems() []*VirtualMachineInstance {
	if x != nil {
		return x.Items
	}
	return nil
}

type VirtualMachineInstanceTemplateSpec struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Metadata      *ObjectMeta                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *VirtualMachineInstanceSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineInstanceTemplateSpec) Reset() {
	*x = VirtualMachineInstanceTemplateSpec{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineInstanceTemplateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineInstanceTemplateSpec) ProtoMessage() {}

func (x *VirtualMachineInstanceTemplateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineInstanceTemplateSpec.ProtoReflect.Descriptor instead.
func (*VirtualMachineInstanceTemplateSpec) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{14}
}

func (x *VirtualMachineInstanceTemplateSpec) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VirtualMachineInstanceTemplateSpec) GetSpec() *VirtualMachineInstanceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type Disk_Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bus           string                 `protobuf:"bytes,1,opt,name=bus,proto3" json:"bus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk_Disk) Reset() {
	*x = Disk_Disk{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk_Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk_Disk) ProtoMessage() {}

func (x *Disk_Disk) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk_Disk.ProtoReflect.Descriptor instead.
func (*Disk_Disk) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Disk_Disk) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

type Network_Multus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkName   string                 `protobuf:"bytes,1,opt,name=networkName,proto3" json:"networkName,omitempty"`
	Default       *bool                  `protobuf:"varint,2,opt,name=default,proto3,oneof" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network_Multus) Reset() {
	*x = Network_Multus{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network_Multus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network_Multus) ProtoMessage() {}

func (x *Network_Multus) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network_Multus.ProtoReflect.Descriptor instead.
func (*Network_Multus) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Network_Multus) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *Network_Multus) GetDefault() bool {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return false
}

type Volume_DataVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume_DataVolume) Reset() {
	*x = Volume_DataVolume{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume_DataVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume_DataVolume) ProtoMessage() {}

func (x *Volume_DataVolume) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume_DataVolume.ProtoReflect.Descriptor instead.
func (*Volume_DataVolume) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{11, 0}
}

func (x *Volume_DataVolume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Volume_CloudInitNoCloud struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserData       *string                `protobuf:"bytes,1,opt,name=userData,proto3,oneof" json:"userData,omitempty"`
	UserDataBase64 *string                `protobuf:"bytes,2,opt,name=userDataBase64,proto3,oneof" json:"userDataBase64,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Volume_CloudInitNoCloud) Reset() {
	*x = Volume_CloudInitNoCloud{}
	mi := &file_types_virtualmachineinstance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume_CloudInitNoCloud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume_CloudInitNoCloud) ProtoMessage() {}

func (x *Volume_CloudInitNoCloud) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachineinstance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume_CloudInitNoCloud.ProtoReflect.Descriptor instead.
func (*Volume_CloudInitNoCloud) Descriptor() ([]byte, []int) {
	return file_types_virtualmachineinstance_proto_rawDescGZIP(), []int{11, 1}
}

func (x *Volume_CloudInitNoCloud) GetUserData() string {
	if x != nil && x.UserData != nil {
		return *x.UserData
	}
	return ""
}

func (x *Volume_CloudInitNoCloud) GetUserDataBase64() string {
	if x != nil && x.UserDataBase64 != nil {
		return *x.UserDataBase64
	}
	return ""
}

var File_types_virtualmachineinstance_proto protoreflect.FileDescriptor

const file_types_virtualmachineinstance_proto_rawDesc = "" +
	"\n" +
	"\"types/virtualmachineinstance.proto\x12\x19vink.kubevm.io.apis.types\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14types/metadata.proto\"\xab\x02\n" +
	"\x16VirtualMachineInstance\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12A\n" +
	"\bmetadata\x18\x03 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12I\n" +
	"\x04spec\x18\x04 \x01(\v25.vink.kubevm.io.apis.types.VirtualMachineInstanceSpecR\x04spec\x12O\n" +
	"\x06status\x18\x05 \x01(\v27.vink.kubevm.io.apis.types.VirtualMachineInstanceStatusR\x06status\"\xfc\x01\n" +
	"\x1aVirtualMachineInstanceSpec\x12\"\n" +
	"\farchitecture\x18\x01 \x01(\tR\farchitecture\x12=\n" +
	"\x06domain\x18\x02 \x01(\v2%.vink.kubevm.io.apis.types.DomainSpecR\x06domain\x12>\n" +
	"\bnetworks\x18\x03 \x03(\v2\".vink.kubevm.io.apis.types.NetworkR\bnetworks\x12;\n" +
	"\avolumes\x18\x04 \x03(\v2!.vink.kubevm.io.apis.types.VolumeR\avolumes\"\xfb\x01\n" +
	"\n" +
	"DomainSpec\x120\n" +
	"\x03cpu\x18\x01 \x01(\v2\x1e.vink.kubevm.io.apis.types.CpuR\x03cpu\x129\n" +
	"\x06memory\x18\x02 \x01(\v2!.vink.kubevm.io.apis.types.MemoryR\x06memory\x12B\n" +
	"\tresources\x18\x03 \x01(\v2$.vink.kubevm.io.apis.types.ResourcesR\tresources\x12<\n" +
	"\adevices\x18\x04 \x01(\v2\".vink.kubevm.io.apis.types.DevicesR\adevices\"Z\n" +
	"\x03Cpu\x12\x14\n" +
	"\x05cores\x18\x01 \x01(\rR\x05cores\x12\x18\n" +
	"\athreads\x18\x02 \x01(\rR\athreads\x12\x19\n" +
	"\x05model\x18\x03 \x01(\tH\x00R\x05model\x88\x01\x01B\b\n" +
	"\x06_model\"\x1e\n" +
	"\x06Memory\x12\x14\n" +
	"\x05guest\x18\x01 \x01(\tR\x05guest\"\x89\x01\n" +
	"\tResources\x12?\n" +
	"\brequests\x18\x01 \x01(\v2#.vink.kubevm.io.apis.types.RequestsR\brequests\x12;\n" +
	"\x06limits\x18\x02 \x01(\v2#.vink.kubevm.io.apis.types.RequestsR\x06limits\"4\n" +
	"\bRequests\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\tR\x06memory\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\tR\x03cpu\"\x86\x01\n" +
	"\aDevices\x125\n" +
	"\x05disks\x18\x01 \x03(\v2\x1f.vink.kubevm.io.apis.types.DiskR\x05disks\x12D\n" +
	"\n" +
	"interfaces\x18\x02 \x03(\v2$.vink.kubevm.io.apis.types.InterfaceR\n" +
	"interfaces\"\x9f\x01\n" +
	"\x04Disk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\tbootOrder\x18\x02 \x01(\x05H\x00R\tbootOrder\x88\x01\x01\x128\n" +
	"\x04disk\x18\x03 \x01(\v2$.vink.kubevm.io.apis.types.Disk.DiskR\x04disk\x1a\x18\n" +
	"\x04Disk\x12\x10\n" +
	"\x03bus\x18\x01 \x01(\tR\x03busB\f\n" +
	"\n" +
	"_bootOrder\"\xe8\x01\n" +
	"\tInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x06bridge\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06bridge\x88\x01\x01\x12;\n" +
	"\n" +
	"masquerade\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x01R\n" +
	"masquerade\x88\x01\x01\x121\n" +
	"\x05sriov\x18\x04 \x01(\v2\x16.google.protobuf.EmptyH\x02R\x05sriov\x88\x01\x01B\t\n" +
	"\a_bridgeB\r\n" +
	"\v_masqueradeB\b\n" +
	"\x06_sriov\"\xc7\x01\n" +
	"\aNetwork\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\x06multus\x18\x02 \x01(\v2).vink.kubevm.io.apis.types.Network.MultusH\x00R\x06multus\x88\x01\x01\x1aU\n" +
	"\x06Multus\x12 \n" +
	"\vnetworkName\x18\x01 \x01(\tR\vnetworkName\x12\x1d\n" +
	"\adefault\x18\x02 \x01(\bH\x00R\adefault\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\t\n" +
	"\a_multus\"\x9d\x03\n" +
	"\x06Volume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12Q\n" +
	"\n" +
	"dataVolume\x18\x02 \x01(\v2,.vink.kubevm.io.apis.types.Volume.DataVolumeH\x00R\n" +
	"dataVolume\x88\x01\x01\x12c\n" +
	"\x10cloudInitNoCloud\x18\x03 \x01(\v22.vink.kubevm.io.apis.types.Volume.CloudInitNoCloudH\x01R\x10cloudInitNoCloud\x88\x01\x01\x1a \n" +
	"\n" +
	"DataVolume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a\x80\x01\n" +
	"\x10CloudInitNoCloud\x12\x1f\n" +
	"\buserData\x18\x01 \x01(\tH\x00R\buserData\x88\x01\x01\x12+\n" +
	"\x0euserDataBase64\x18\x02 \x01(\tH\x01R\x0euserDataBase64\x88\x01\x01B\v\n" +
	"\t_userDataB\x11\n" +
	"\x0f_userDataBase64B\r\n" +
	"\v_dataVolumeB\x13\n" +
	"\x11_cloudInitNoCloud\"\x1e\n" +
	"\x1cVirtualMachineInstanceStatus\"e\n" +
	"\x1aVirtualMachineInstanceList\x12G\n" +
	"\x05items\x18\x01 \x03(\v21.vink.kubevm.io.apis.types.VirtualMachineInstanceR\x05items\"\xb2\x01\n" +
	"\"VirtualMachineInstanceTemplateSpec\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12I\n" +
	"\x04spec\x18\x02 \x01(\v25.vink.kubevm.io.apis.types.VirtualMachineInstanceSpecR\x04specB&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_virtualmachineinstance_proto_rawDescOnce sync.Once
	file_types_virtualmachineinstance_proto_rawDescData []byte
)

func file_types_virtualmachineinstance_proto_rawDescGZIP() []byte {
	file_types_virtualmachineinstance_proto_rawDescOnce.Do(func() {
		file_types_virtualmachineinstance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_virtualmachineinstance_proto_rawDesc), len(file_types_virtualmachineinstance_proto_rawDesc)))
	})
	return file_types_virtualmachineinstance_proto_rawDescData
}

var file_types_virtualmachineinstance_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_types_virtualmachineinstance_proto_goTypes = []any{
	(*VirtualMachineInstance)(nil),             // 0: vink.kubevm.io.apis.types.VirtualMachineInstance
	(*VirtualMachineInstanceSpec)(nil),         // 1: vink.kubevm.io.apis.types.VirtualMachineInstanceSpec
	(*DomainSpec)(nil),                         // 2: vink.kubevm.io.apis.types.DomainSpec
	(*Cpu)(nil),                                // 3: vink.kubevm.io.apis.types.Cpu
	(*Memory)(nil),                             // 4: vink.kubevm.io.apis.types.Memory
	(*Resources)(nil),                          // 5: vink.kubevm.io.apis.types.Resources
	(*Requests)(nil),                           // 6: vink.kubevm.io.apis.types.Requests
	(*Devices)(nil),                            // 7: vink.kubevm.io.apis.types.Devices
	(*Disk)(nil),                               // 8: vink.kubevm.io.apis.types.Disk
	(*Interface)(nil),                          // 9: vink.kubevm.io.apis.types.Interface
	(*Network)(nil),                            // 10: vink.kubevm.io.apis.types.Network
	(*Volume)(nil),                             // 11: vink.kubevm.io.apis.types.Volume
	(*VirtualMachineInstanceStatus)(nil),       // 12: vink.kubevm.io.apis.types.VirtualMachineInstanceStatus
	(*VirtualMachineInstanceList)(nil),         // 13: vink.kubevm.io.apis.types.VirtualMachineInstanceList
	(*VirtualMachineInstanceTemplateSpec)(nil), // 14: vink.kubevm.io.apis.types.VirtualMachineInstanceTemplateSpec
	(*Disk_Disk)(nil),                          // 15: vink.kubevm.io.apis.types.Disk.Disk
	(*Network_Multus)(nil),                     // 16: vink.kubevm.io.apis.types.Network.Multus
	(*Volume_DataVolume)(nil),                  // 17: vink.kubevm.io.apis.types.Volume.DataVolume
	(*Volume_CloudInitNoCloud)(nil),            // 18: vink.kubevm.io.apis.types.Volume.CloudInitNoCloud
	(*ObjectMeta)(nil),                         // 19: vink.kubevm.io.apis.types.ObjectMeta
	(*emptypb.Empty)(nil),                      // 20: google.protobuf.Empty
}
var file_types_virtualmachineinstance_proto_depIdxs = []int32{
	19, // 0: vink.kubevm.io.apis.types.VirtualMachineInstance.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	1,  // 1: vink.kubevm.io.apis.types.VirtualMachineInstance.spec:type_name -> vink.kubevm.io.apis.types.VirtualMachineInstanceSpec
	12, // 2: vink.kubevm.io.apis.types.VirtualMachineInstance.status:type_name -> vink.kubevm.io.apis.types.VirtualMachineInstanceStatus
	2,  // 3: vink.kubevm.io.apis.types.VirtualMachineInstanceSpec.domain:type_name -> vink.kubevm.io.apis.types.DomainSpec
	10, // 4: vink.kubevm.io.apis.types.VirtualMachineInstanceSpec.networks:type_name -> vink.kubevm.io.apis.types.Network
	11, // 5: vink.kubevm.io.apis.types.VirtualMachineInstanceSpec.volumes:type_name -> vink.kubevm.io.apis.types.Volume
	3,  // 6: vink.kubevm.io.apis.types.DomainSpec.cpu:type_name -> vink.kubevm.io.apis.types.Cpu
	4,  // 7: vink.kubevm.io.apis.types.DomainSpec.memory:type_name -> vink.kubevm.io.apis.types.Memory
	5,  // 8: vink.kubevm.io.apis.types.DomainSpec.resources:type_name -> vink.kubevm.io.apis.types.Resources
	7,  // 9: vink.kubevm.io.apis.types.DomainSpec.devices:type_name -> vink.kubevm.io.apis.types.Devices
	6,  // 10: vink.kubevm.io.apis.types.Resources.requests:type_name -> vink.kubevm.io.apis.types.Requests
	6,  // 11: vink.kubevm.io.apis.types.Resources.limits:type_name -> vink.kubevm.io.apis.types.Requests
	8,  // 12: vink.kubevm.io.apis.types.Devices.disks:type_name -> vink.kubevm.io.apis.types.Disk
	9,  // 13: vink.kubevm.io.apis.types.Devices.interfaces:type_name -> vink.kubevm.io.apis.types.Interface
	15, // 14: vink.kubevm.io.apis.types.Disk.disk:type_name -> vink.kubevm.io.apis.types.Disk.Disk
	20, // 15: vink.kubevm.io.apis.types.Interface.bridge:type_name -> google.protobuf.Empty
	20, // 16: vink.kubevm.io.apis.types.Interface.masquerade:type_name -> google.protobuf.Empty
	20, // 17: vink.kubevm.io.apis.types.Interface.sriov:type_name -> google.protobuf.Empty
	16, // 18: vink.kubevm.io.apis.types.Network.multus:type_name -> vink.kubevm.io.apis.types.Network.Multus
	17, // 19: vink.kubevm.io.apis.types.Volume.dataVolume:type_name -> vink.kubevm.io.apis.types.Volume.DataVolume
	18, // 20: vink.kubevm.io.apis.types.Volume.cloudInitNoCloud:type_name -> vink.kubevm.io.apis.types.Volume.CloudInitNoCloud
	0,  // 21: vink.kubevm.io.apis.types.VirtualMachineInstanceList.items:type_name -> vink.kubevm.io.apis.types.VirtualMachineInstance
	19, // 22: vink.kubevm.io.apis.types.VirtualMachineInstanceTemplateSpec.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	1,  // 23: vink.kubevm.io.apis.types.VirtualMachineInstanceTemplateSpec.spec:type_name -> vink.kubevm.io.apis.types.VirtualMachineInstanceSpec
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_types_virtualmachineinstance_proto_init() }
func file_types_virtualmachineinstance_proto_init() {
	if File_types_virtualmachineinstance_proto != nil {
		return
	}
	file_types_metadata_proto_init()
	file_types_virtualmachineinstance_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_virtualmachineinstance_proto_msgTypes[8].OneofWrappers = []any{}
	file_types_virtualmachineinstance_proto_msgTypes[9].OneofWrappers = []any{}
	file_types_virtualmachineinstance_proto_msgTypes[10].OneofWrappers = []any{}
	file_types_virtualmachineinstance_proto_msgTypes[11].OneofWrappers = []any{}
	file_types_virtualmachineinstance_proto_msgTypes[16].OneofWrappers = []any{}
	file_types_virtualmachineinstance_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_virtualmachineinstance_proto_rawDesc), len(file_types_virtualmachineinstance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_virtualmachineinstance_proto_goTypes,
		DependencyIndexes: file_types_virtualmachineinstance_proto_depIdxs,
		MessageInfos:      file_types_virtualmachineinstance_proto_msgTypes,
	}.Build()
	File_types_virtualmachineinstance_proto = out.File
	file_types_virtualmachineinstance_proto_goTypes = nil
	file_types_virtualmachineinstance_proto_depIdxs = nil
}
