// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/virtualmachinesnapshot.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualMachineSnapshot struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Kind          string                        `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion    string                        `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Metadata      *ObjectMeta                   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *VirtualMachineSnapshotSpec   `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VirtualMachineSnapshotStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineSnapshot) Reset() {
	*x = VirtualMachineSnapshot{}
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineSnapshot) ProtoMessage() {}

func (x *VirtualMachineSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineSnapshot.ProtoReflect.Descriptor instead.
func (*VirtualMachineSnapshot) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinesnapshot_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachineSnapshot) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VirtualMachineSnapshot) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *VirtualMachineSnapshot) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VirtualMachineSnapshot) GetSpec() *VirtualMachineSnapshotSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *VirtualMachineSnapshot) GetStatus() *VirtualMachineSnapshotStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type VirtualMachineSnapshotList struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*VirtualMachineSnapshot `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineSnapshotList) Reset() {
	*x = VirtualMachineSnapshotList{}
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineSnapshotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineSnapshotList) ProtoMessage() {}

func (x *VirtualMachineSnapshotList) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineSnapshotList.ProtoReflect.Descriptor instead.
func (*VirtualMachineSnapshotList) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinesnapshot_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualMachineSnapshotList) GetItems() []*VirtualMachineSnapshot {
	if x != nil {
		return x.Items
	}
	return nil
}

type VirtualMachineSnapshotSpec struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Source        *VirtualMachineSnapshotSpec_Reference `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineSnapshotSpec) Reset() {
	*x = VirtualMachineSnapshotSpec{}
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineSnapshotSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineSnapshotSpec) ProtoMessage() {}

func (x *VirtualMachineSnapshotSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineSnapshotSpec.ProtoReflect.Descriptor instead.
func (*VirtualMachineSnapshotSpec) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinesnapshot_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualMachineSnapshotSpec) GetSource() *VirtualMachineSnapshotSpec_Reference {
	if x != nil {
		return x.Source
	}
	return nil
}

type VirtualMachineSnapshotStatus struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Phase         string                              `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	ReadyToUse    bool                                `protobuf:"varint,2,opt,name=readyToUse,proto3" json:"readyToUse,omitempty"`
	Error         *VirtualMachineSnapshotStatus_Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Conditions    []*Condition                        `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineSnapshotStatus) Reset() {
	*x = VirtualMachineSnapshotStatus{}
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineSnapshotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineSnapshotStatus) ProtoMessage() {}

func (x *VirtualMachineSnapshotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineSnapshotStatus.ProtoReflect.Descriptor instead.
func (*VirtualMachineSnapshotStatus) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinesnapshot_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualMachineSnapshotStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *VirtualMachineSnapshotStatus) GetReadyToUse() bool {
	if x != nil {
		return x.ReadyToUse
	}
	return false
}

func (x *VirtualMachineSnapshotStatus) GetError() *VirtualMachineSnapshotStatus_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *VirtualMachineSnapshotStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type VirtualMachineSnapshotSpec_Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiGroup      string                 `protobuf:"bytes,1,opt,name=apiGroup,proto3" json:"apiGroup,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineSnapshotSpec_Reference) Reset() {
	*x = VirtualMachineSnapshotSpec_Reference{}
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineSnapshotSpec_Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineSnapshotSpec_Reference) ProtoMessage() {}

func (x *VirtualMachineSnapshotSpec_Reference) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineSnapshotSpec_Reference.ProtoReflect.Descriptor instead.
func (*VirtualMachineSnapshotSpec_Reference) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinesnapshot_proto_rawDescGZIP(), []int{2, 0}
}

func (x *VirtualMachineSnapshotSpec_Reference) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *VirtualMachineSnapshotSpec_Reference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VirtualMachineSnapshotSpec_Reference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VirtualMachineSnapshotStatus_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineSnapshotStatus_Error) Reset() {
	*x = VirtualMachineSnapshotStatus_Error{}
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineSnapshotStatus_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineSnapshotStatus_Error) ProtoMessage() {}

func (x *VirtualMachineSnapshotStatus_Error) ProtoReflect() protoreflect.Message {
	mi := &file_types_virtualmachinesnapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineSnapshotStatus_Error.ProtoReflect.Descriptor instead.
func (*VirtualMachineSnapshotStatus_Error) Descriptor() ([]byte, []int) {
	return file_types_virtualmachinesnapshot_proto_rawDescGZIP(), []int{3, 0}
}

func (x *VirtualMachineSnapshotStatus_Error) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *VirtualMachineSnapshotStatus_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_types_virtualmachinesnapshot_proto protoreflect.FileDescriptor

const file_types_virtualmachinesnapshot_proto_rawDesc = "" +
	"\n" +
	"\"types/virtualmachinesnapshot.proto\x12\x19vink.kubevm.io.apis.types\x1a\x14types/metadata.proto\x1a\x11types/types.proto\"\xab\x02\n" +
	"\x16VirtualMachineSnapshot\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12A\n" +
	"\bmetadata\x18\x03 \x01(\v2%.vink.kubevm.io.apis.types.ObjectMetaR\bmetadata\x12I\n" +
	"\x04spec\x18\x04 \x01(\v25.vink.kubevm.io.apis.types.VirtualMachineSnapshotSpecR\x04spec\x12O\n" +
	"\x06status\x18\x05 \x01(\v27.vink.kubevm.io.apis.types.VirtualMachineSnapshotStatusR\x06status\"e\n" +
	"\x1aVirtualMachineSnapshotList\x12G\n" +
	"\x05items\x18\x01 \x03(\v21.vink.kubevm.io.apis.types.VirtualMachineSnapshotR\x05items\"\xc6\x01\n" +
	"\x1aVirtualMachineSnapshotSpec\x12W\n" +
	"\x06source\x18\x01 \x01(\v2?.vink.kubevm.io.apis.types.VirtualMachineSnapshotSpec.ReferenceR\x06source\x1aO\n" +
	"\tReference\x12\x1a\n" +
	"\bapiGroup\x18\x01 \x01(\tR\bapiGroup\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xa6\x02\n" +
	"\x1cVirtualMachineSnapshotStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1e\n" +
	"\n" +
	"readyToUse\x18\x02 \x01(\bR\n" +
	"readyToUse\x12S\n" +
	"\x05error\x18\x03 \x01(\v2=.vink.kubevm.io.apis.types.VirtualMachineSnapshotStatus.ErrorR\x05error\x12D\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2$.vink.kubevm.io.apis.types.ConditionR\n" +
	"conditions\x1a5\n" +
	"\x05Error\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB&Z$github.com/kubevm.io/vink/apis/typesb\x06proto3"

var (
	file_types_virtualmachinesnapshot_proto_rawDescOnce sync.Once
	file_types_virtualmachinesnapshot_proto_rawDescData []byte
)

func file_types_virtualmachinesnapshot_proto_rawDescGZIP() []byte {
	file_types_virtualmachinesnapshot_proto_rawDescOnce.Do(func() {
		file_types_virtualmachinesnapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_virtualmachinesnapshot_proto_rawDesc), len(file_types_virtualmachinesnapshot_proto_rawDesc)))
	})
	return file_types_virtualmachinesnapshot_proto_rawDescData
}

var file_types_virtualmachinesnapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_virtualmachinesnapshot_proto_goTypes = []any{
	(*VirtualMachineSnapshot)(nil),               // 0: vink.kubevm.io.apis.types.VirtualMachineSnapshot
	(*VirtualMachineSnapshotList)(nil),           // 1: vink.kubevm.io.apis.types.VirtualMachineSnapshotList
	(*VirtualMachineSnapshotSpec)(nil),           // 2: vink.kubevm.io.apis.types.VirtualMachineSnapshotSpec
	(*VirtualMachineSnapshotStatus)(nil),         // 3: vink.kubevm.io.apis.types.VirtualMachineSnapshotStatus
	(*VirtualMachineSnapshotSpec_Reference)(nil), // 4: vink.kubevm.io.apis.types.VirtualMachineSnapshotSpec.Reference
	(*VirtualMachineSnapshotStatus_Error)(nil),   // 5: vink.kubevm.io.apis.types.VirtualMachineSnapshotStatus.Error
	(*ObjectMeta)(nil),                           // 6: vink.kubevm.io.apis.types.ObjectMeta
	(*Condition)(nil),                            // 7: vink.kubevm.io.apis.types.Condition
}
var file_types_virtualmachinesnapshot_proto_depIdxs = []int32{
	6, // 0: vink.kubevm.io.apis.types.VirtualMachineSnapshot.metadata:type_name -> vink.kubevm.io.apis.types.ObjectMeta
	2, // 1: vink.kubevm.io.apis.types.VirtualMachineSnapshot.spec:type_name -> vink.kubevm.io.apis.types.VirtualMachineSnapshotSpec
	3, // 2: vink.kubevm.io.apis.types.VirtualMachineSnapshot.status:type_name -> vink.kubevm.io.apis.types.VirtualMachineSnapshotStatus
	0, // 3: vink.kubevm.io.apis.types.VirtualMachineSnapshotList.items:type_name -> vink.kubevm.io.apis.types.VirtualMachineSnapshot
	4, // 4: vink.kubevm.io.apis.types.VirtualMachineSnapshotSpec.source:type_name -> vink.kubevm.io.apis.types.VirtualMachineSnapshotSpec.Reference
	5, // 5: vink.kubevm.io.apis.types.VirtualMachineSnapshotStatus.error:type_name -> vink.kubevm.io.apis.types.VirtualMachineSnapshotStatus.Error
	7, // 6: vink.kubevm.io.apis.types.VirtualMachineSnapshotStatus.conditions:type_name -> vink.kubevm.io.apis.types.Condition
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_types_virtualmachinesnapshot_proto_init() }
func file_types_virtualmachinesnapshot_proto_init() {
	if File_types_virtualmachinesnapshot_proto != nil {
		return
	}
	file_types_metadata_proto_init()
	file_types_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_virtualmachinesnapshot_proto_rawDesc), len(file_types_virtualmachinesnapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_virtualmachinesnapshot_proto_goTypes,
		DependencyIndexes: file_types_virtualmachinesnapshot_proto_depIdxs,
		MessageInfos:      file_types_virtualmachinesnapshot_proto_msgTypes,
	}.Build()
	File_types_virtualmachinesnapshot_proto = out.File
	file_types_virtualmachinesnapshot_proto_goTypes = nil
	file_types_virtualmachinesnapshot_proto_depIdxs = nil
}
