// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using VirtualMachine within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachine) DeepCopyInto(out *VirtualMachine) {
	p := proto.Clone(in).(*VirtualMachine)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachine. Required by controller-gen.
func (in *VirtualMachine) DeepCopy() *VirtualMachine {
	if in == nil {
		return nil
	}
	out := new(VirtualMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachine. Required by controller-gen.
func (in *VirtualMachine) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineSpec within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineSpec) DeepCopyInto(out *VirtualMachineSpec) {
	p := proto.Clone(in).(*VirtualMachineSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineSpec. Required by controller-gen.
func (in *VirtualMachineSpec) DeepCopy() *VirtualMachineSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineSpec. Required by controller-gen.
func (in *VirtualMachineSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineStatus within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineStatus) DeepCopyInto(out *VirtualMachineStatus) {
	p := proto.Clone(in).(*VirtualMachineStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStatus. Required by controller-gen.
func (in *VirtualMachineStatus) DeepCopy() *VirtualMachineStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStatus. Required by controller-gen.
func (in *VirtualMachineStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineStatus_VolumeSnapshotStatus within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineStatus_VolumeSnapshotStatus) DeepCopyInto(out *VirtualMachineStatus_VolumeSnapshotStatus) {
	p := proto.Clone(in).(*VirtualMachineStatus_VolumeSnapshotStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStatus_VolumeSnapshotStatus. Required by controller-gen.
func (in *VirtualMachineStatus_VolumeSnapshotStatus) DeepCopy() *VirtualMachineStatus_VolumeSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStatus_VolumeSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStatus_VolumeSnapshotStatus. Required by controller-gen.
func (in *VirtualMachineStatus_VolumeSnapshotStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineList within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineList) DeepCopyInto(out *VirtualMachineList) {
	p := proto.Clone(in).(*VirtualMachineList)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineList. Required by controller-gen.
func (in *VirtualMachineList) DeepCopy() *VirtualMachineList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineList. Required by controller-gen.
func (in *VirtualMachineList) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineHost within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineHost) DeepCopyInto(out *VirtualMachineHost) {
	p := proto.Clone(in).(*VirtualMachineHost)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineHost. Required by controller-gen.
func (in *VirtualMachineHost) DeepCopy() *VirtualMachineHost {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineHost. Required by controller-gen.
func (in *VirtualMachineHost) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataVolumeTemplate within kubernetes types, where deepcopy-gen is used.
func (in *DataVolumeTemplate) DeepCopyInto(out *DataVolumeTemplate) {
	p := proto.Clone(in).(*DataVolumeTemplate)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplate. Required by controller-gen.
func (in *DataVolumeTemplate) DeepCopy() *DataVolumeTemplate {
	if in == nil {
		return nil
	}
	out := new(DataVolumeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplate. Required by controller-gen.
func (in *DataVolumeTemplate) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataVolumeTemplateSpec within kubernetes types, where deepcopy-gen is used.
func (in *DataVolumeTemplateSpec) DeepCopyInto(out *DataVolumeTemplateSpec) {
	p := proto.Clone(in).(*DataVolumeTemplateSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec. Required by controller-gen.
func (in *DataVolumeTemplateSpec) DeepCopy() *DataVolumeTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DataVolumeTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec. Required by controller-gen.
func (in *DataVolumeTemplateSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataVolumeTemplateSpec_Pvc within kubernetes types, where deepcopy-gen is used.
func (in *DataVolumeTemplateSpec_Pvc) DeepCopyInto(out *DataVolumeTemplateSpec_Pvc) {
	p := proto.Clone(in).(*DataVolumeTemplateSpec_Pvc)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Pvc. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Pvc) DeepCopy() *DataVolumeTemplateSpec_Pvc {
	if in == nil {
		return nil
	}
	out := new(DataVolumeTemplateSpec_Pvc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Pvc. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Pvc) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataVolumeTemplateSpec_Pvc_Resources within kubernetes types, where deepcopy-gen is used.
func (in *DataVolumeTemplateSpec_Pvc_Resources) DeepCopyInto(out *DataVolumeTemplateSpec_Pvc_Resources) {
	p := proto.Clone(in).(*DataVolumeTemplateSpec_Pvc_Resources)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Pvc_Resources. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Pvc_Resources) DeepCopy() *DataVolumeTemplateSpec_Pvc_Resources {
	if in == nil {
		return nil
	}
	out := new(DataVolumeTemplateSpec_Pvc_Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Pvc_Resources. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Pvc_Resources) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataVolumeTemplateSpec_Pvc_Resources_Requests within kubernetes types, where deepcopy-gen is used.
func (in *DataVolumeTemplateSpec_Pvc_Resources_Requests) DeepCopyInto(out *DataVolumeTemplateSpec_Pvc_Resources_Requests) {
	p := proto.Clone(in).(*DataVolumeTemplateSpec_Pvc_Resources_Requests)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Pvc_Resources_Requests. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Pvc_Resources_Requests) DeepCopy() *DataVolumeTemplateSpec_Pvc_Resources_Requests {
	if in == nil {
		return nil
	}
	out := new(DataVolumeTemplateSpec_Pvc_Resources_Requests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Pvc_Resources_Requests. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Pvc_Resources_Requests) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataVolumeTemplateSpec_Source within kubernetes types, where deepcopy-gen is used.
func (in *DataVolumeTemplateSpec_Source) DeepCopyInto(out *DataVolumeTemplateSpec_Source) {
	p := proto.Clone(in).(*DataVolumeTemplateSpec_Source)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Source. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Source) DeepCopy() *DataVolumeTemplateSpec_Source {
	if in == nil {
		return nil
	}
	out := new(DataVolumeTemplateSpec_Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Source. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Source) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataVolumeTemplateSpec_Source_Http within kubernetes types, where deepcopy-gen is used.
func (in *DataVolumeTemplateSpec_Source_Http) DeepCopyInto(out *DataVolumeTemplateSpec_Source_Http) {
	p := proto.Clone(in).(*DataVolumeTemplateSpec_Source_Http)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Source_Http. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Source_Http) DeepCopy() *DataVolumeTemplateSpec_Source_Http {
	if in == nil {
		return nil
	}
	out := new(DataVolumeTemplateSpec_Source_Http)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Source_Http. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Source_Http) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataVolumeTemplateSpec_Source_Blank within kubernetes types, where deepcopy-gen is used.
func (in *DataVolumeTemplateSpec_Source_Blank) DeepCopyInto(out *DataVolumeTemplateSpec_Source_Blank) {
	p := proto.Clone(in).(*DataVolumeTemplateSpec_Source_Blank)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Source_Blank. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Source_Blank) DeepCopy() *DataVolumeTemplateSpec_Source_Blank {
	if in == nil {
		return nil
	}
	out := new(DataVolumeTemplateSpec_Source_Blank)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeTemplateSpec_Source_Blank. Required by controller-gen.
func (in *DataVolumeTemplateSpec_Source_Blank) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineResourceMetrics within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineResourceMetrics) DeepCopyInto(out *VirtualMachineResourceMetrics) {
	p := proto.Clone(in).(*VirtualMachineResourceMetrics)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineResourceMetrics. Required by controller-gen.
func (in *VirtualMachineResourceMetrics) DeepCopy() *VirtualMachineResourceMetrics {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineResourceMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineResourceMetrics. Required by controller-gen.
func (in *VirtualMachineResourceMetrics) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineNetwork within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineNetwork) DeepCopyInto(out *VirtualMachineNetwork) {
	p := proto.Clone(in).(*VirtualMachineNetwork)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNetwork. Required by controller-gen.
func (in *VirtualMachineNetwork) DeepCopy() *VirtualMachineNetwork {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNetwork. Required by controller-gen.
func (in *VirtualMachineNetwork) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineDisk within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineDisk) DeepCopyInto(out *VirtualMachineDisk) {
	p := proto.Clone(in).(*VirtualMachineDisk)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDisk. Required by controller-gen.
func (in *VirtualMachineDisk) DeepCopy() *VirtualMachineDisk {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDisk. Required by controller-gen.
func (in *VirtualMachineDisk) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
