// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using VirtualMachineClone within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineClone) DeepCopyInto(out *VirtualMachineClone) {
	p := proto.Clone(in).(*VirtualMachineClone)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineClone. Required by controller-gen.
func (in *VirtualMachineClone) DeepCopy() *VirtualMachineClone {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineClone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineClone. Required by controller-gen.
func (in *VirtualMachineClone) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineCloneList within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineCloneList) DeepCopyInto(out *VirtualMachineCloneList) {
	p := proto.Clone(in).(*VirtualMachineCloneList)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneList. Required by controller-gen.
func (in *VirtualMachineCloneList) DeepCopy() *VirtualMachineCloneList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineCloneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneList. Required by controller-gen.
func (in *VirtualMachineCloneList) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineCloneSpec within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineCloneSpec) DeepCopyInto(out *VirtualMachineCloneSpec) {
	p := proto.Clone(in).(*VirtualMachineCloneSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneSpec. Required by controller-gen.
func (in *VirtualMachineCloneSpec) DeepCopy() *VirtualMachineCloneSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineCloneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneSpec. Required by controller-gen.
func (in *VirtualMachineCloneSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineCloneSpec_Reference within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineCloneSpec_Reference) DeepCopyInto(out *VirtualMachineCloneSpec_Reference) {
	p := proto.Clone(in).(*VirtualMachineCloneSpec_Reference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneSpec_Reference. Required by controller-gen.
func (in *VirtualMachineCloneSpec_Reference) DeepCopy() *VirtualMachineCloneSpec_Reference {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineCloneSpec_Reference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneSpec_Reference. Required by controller-gen.
func (in *VirtualMachineCloneSpec_Reference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VirtualMachineCloneStatus within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachineCloneStatus) DeepCopyInto(out *VirtualMachineCloneStatus) {
	p := proto.Clone(in).(*VirtualMachineCloneStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneStatus. Required by controller-gen.
func (in *VirtualMachineCloneStatus) DeepCopy() *VirtualMachineCloneStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineCloneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneStatus. Required by controller-gen.
func (in *VirtualMachineCloneStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
