// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Resource within kubernetes types, where deepcopy-gen is used.
func (in *Resource) DeepCopyInto(out *Resource) {
	p := proto.Clone(in).(*Resource)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource. Required by controller-gen.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Resource. Required by controller-gen.
func (in *Resource) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetRequest) DeepCopyInto(out *GetRequest) {
	p := proto.Clone(in).(*GetRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRequest. Required by controller-gen.
func (in *GetRequest) DeepCopy() *GetRequest {
	if in == nil {
		return nil
	}
	out := new(GetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetRequest. Required by controller-gen.
func (in *GetRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListRequest) DeepCopyInto(out *ListRequest) {
	p := proto.Clone(in).(*ListRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListRequest. Required by controller-gen.
func (in *ListRequest) DeepCopy() *ListRequest {
	if in == nil {
		return nil
	}
	out := new(ListRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListRequest. Required by controller-gen.
func (in *ListRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListResponse) DeepCopyInto(out *ListResponse) {
	p := proto.Clone(in).(*ListResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListResponse. Required by controller-gen.
func (in *ListResponse) DeepCopy() *ListResponse {
	if in == nil {
		return nil
	}
	out := new(ListResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListResponse. Required by controller-gen.
func (in *ListResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateRequest) DeepCopyInto(out *CreateRequest) {
	p := proto.Clone(in).(*CreateRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateRequest. Required by controller-gen.
func (in *CreateRequest) DeepCopy() *CreateRequest {
	if in == nil {
		return nil
	}
	out := new(CreateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateRequest. Required by controller-gen.
func (in *CreateRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateRequest) DeepCopyInto(out *UpdateRequest) {
	p := proto.Clone(in).(*UpdateRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRequest. Required by controller-gen.
func (in *UpdateRequest) DeepCopy() *UpdateRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRequest. Required by controller-gen.
func (in *UpdateRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteRequest) DeepCopyInto(out *DeleteRequest) {
	p := proto.Clone(in).(*DeleteRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRequest. Required by controller-gen.
func (in *DeleteRequest) DeepCopy() *DeleteRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRequest. Required by controller-gen.
func (in *DeleteRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListOptions within kubernetes types, where deepcopy-gen is used.
func (in *ListOptions) DeepCopyInto(out *ListOptions) {
	p := proto.Clone(in).(*ListOptions)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListOptions. Required by controller-gen.
func (in *ListOptions) DeepCopy() *ListOptions {
	if in == nil {
		return nil
	}
	out := new(ListOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListOptions. Required by controller-gen.
func (in *ListOptions) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
