// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: management/resource/v1alpha1/watch.proto

package v1alpha1

import (
	types "github.com/kubevm.io/vink/apis/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_READY    EventType = 0
	EventType_ADDED    EventType = 1
	EventType_MODIFIED EventType = 2
	EventType_DELETED  EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "READY",
		1: "ADDED",
		2: "MODIFIED",
		3: "DELETED",
	}
	EventType_value = map[string]int32{
		"READY":    0,
		"ADDED":    1,
		"MODIFIED": 2,
		"DELETED":  3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_management_resource_v1alpha1_watch_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_management_resource_v1alpha1_watch_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_management_resource_v1alpha1_watch_proto_rawDescGZIP(), []int{0}
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  types.ResourceType     `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=vink.kubevm.io.apis.types.ResourceType" json:"resource_type,omitempty"`
	Options       *WatchOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_management_resource_v1alpha1_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_resource_v1alpha1_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_management_resource_v1alpha1_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetResourceType() types.ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return types.ResourceType(0)
}

func (x *WatchRequest) GetOptions() *WatchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     EventType              `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=vink.kubevm.io.apis.management.resource.v1alpha1.EventType" json:"event_type,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_management_resource_v1alpha1_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_resource_v1alpha1_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_management_resource_v1alpha1_watch_proto_rawDescGZIP(), []int{1}
}

func (x *WatchResponse) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_READY
}

func (x *WatchResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type WatchOptions struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	FieldSelectorGroup *types.FieldSelectorGroup `protobuf:"bytes,1,opt,name=field_selector_group,json=fieldSelectorGroup,proto3" json:"field_selector_group,omitempty"` // repeated string field_selector = 1;
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchOptions) Reset() {
	*x = WatchOptions{}
	mi := &file_management_resource_v1alpha1_watch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchOptions) ProtoMessage() {}

func (x *WatchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_management_resource_v1alpha1_watch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchOptions.ProtoReflect.Descriptor instead.
func (*WatchOptions) Descriptor() ([]byte, []int) {
	return file_management_resource_v1alpha1_watch_proto_rawDescGZIP(), []int{2}
}

func (x *WatchOptions) GetFieldSelectorGroup() *types.FieldSelectorGroup {
	if x != nil {
		return x.FieldSelectorGroup
	}
	return nil
}

var File_management_resource_v1alpha1_watch_proto protoreflect.FileDescriptor

const file_management_resource_v1alpha1_watch_proto_rawDesc = "" +
	"\n" +
	"(management/resource/v1alpha1/watch.proto\x120vink.kubevm.io.apis.management.resource.v1alpha1\x1a\x11types/types.proto\"\xb6\x01\n" +
	"\fWatchRequest\x12L\n" +
	"\rresource_type\x18\x01 \x01(\x0e2'.vink.kubevm.io.apis.types.ResourceTypeR\fresourceType\x12X\n" +
	"\aoptions\x18\x02 \x01(\v2>.vink.kubevm.io.apis.management.resource.v1alpha1.WatchOptionsR\aoptions\"\x81\x01\n" +
	"\rWatchResponse\x12Z\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2;.vink.kubevm.io.apis.management.resource.v1alpha1.EventTypeR\teventType\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\"o\n" +
	"\fWatchOptions\x12_\n" +
	"\x14field_selector_group\x18\x01 \x01(\v2-.vink.kubevm.io.apis.types.FieldSelectorGroupR\x12fieldSelectorGroup*<\n" +
	"\tEventType\x12\t\n" +
	"\x05READY\x10\x00\x12\t\n" +
	"\x05ADDED\x10\x01\x12\f\n" +
	"\bMODIFIED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x032\xa6\x01\n" +
	"\x17ResourceWatchManagement\x12\x8a\x01\n" +
	"\x05Watch\x12>.vink.kubevm.io.apis.management.resource.v1alpha1.WatchRequest\x1a?.vink.kubevm.io.apis.management.resource.v1alpha1.WatchResponse0\x01B=Z;github.com/kubevm.io/vink/apis/management/resource/v1alpha1b\x06proto3"

var (
	file_management_resource_v1alpha1_watch_proto_rawDescOnce sync.Once
	file_management_resource_v1alpha1_watch_proto_rawDescData []byte
)

func file_management_resource_v1alpha1_watch_proto_rawDescGZIP() []byte {
	file_management_resource_v1alpha1_watch_proto_rawDescOnce.Do(func() {
		file_management_resource_v1alpha1_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_resource_v1alpha1_watch_proto_rawDesc), len(file_management_resource_v1alpha1_watch_proto_rawDesc)))
	})
	return file_management_resource_v1alpha1_watch_proto_rawDescData
}

var file_management_resource_v1alpha1_watch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_management_resource_v1alpha1_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_management_resource_v1alpha1_watch_proto_goTypes = []any{
	(EventType)(0),                   // 0: vink.kubevm.io.apis.management.resource.v1alpha1.EventType
	(*WatchRequest)(nil),             // 1: vink.kubevm.io.apis.management.resource.v1alpha1.WatchRequest
	(*WatchResponse)(nil),            // 2: vink.kubevm.io.apis.management.resource.v1alpha1.WatchResponse
	(*WatchOptions)(nil),             // 3: vink.kubevm.io.apis.management.resource.v1alpha1.WatchOptions
	(types.ResourceType)(0),          // 4: vink.kubevm.io.apis.types.ResourceType
	(*types.FieldSelectorGroup)(nil), // 5: vink.kubevm.io.apis.types.FieldSelectorGroup
}
var file_management_resource_v1alpha1_watch_proto_depIdxs = []int32{
	4, // 0: vink.kubevm.io.apis.management.resource.v1alpha1.WatchRequest.resource_type:type_name -> vink.kubevm.io.apis.types.ResourceType
	3, // 1: vink.kubevm.io.apis.management.resource.v1alpha1.WatchRequest.options:type_name -> vink.kubevm.io.apis.management.resource.v1alpha1.WatchOptions
	0, // 2: vink.kubevm.io.apis.management.resource.v1alpha1.WatchResponse.event_type:type_name -> vink.kubevm.io.apis.management.resource.v1alpha1.EventType
	5, // 3: vink.kubevm.io.apis.management.resource.v1alpha1.WatchOptions.field_selector_group:type_name -> vink.kubevm.io.apis.types.FieldSelectorGroup
	1, // 4: vink.kubevm.io.apis.management.resource.v1alpha1.ResourceWatchManagement.Watch:input_type -> vink.kubevm.io.apis.management.resource.v1alpha1.WatchRequest
	2, // 5: vink.kubevm.io.apis.management.resource.v1alpha1.ResourceWatchManagement.Watch:output_type -> vink.kubevm.io.apis.management.resource.v1alpha1.WatchResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_management_resource_v1alpha1_watch_proto_init() }
func file_management_resource_v1alpha1_watch_proto_init() {
	if File_management_resource_v1alpha1_watch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_resource_v1alpha1_watch_proto_rawDesc), len(file_management_resource_v1alpha1_watch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_resource_v1alpha1_watch_proto_goTypes,
		DependencyIndexes: file_management_resource_v1alpha1_watch_proto_depIdxs,
		EnumInfos:         file_management_resource_v1alpha1_watch_proto_enumTypes,
		MessageInfos:      file_management_resource_v1alpha1_watch_proto_msgTypes,
	}.Build()
	File_management_resource_v1alpha1_watch_proto = out.File
	file_management_resource_v1alpha1_watch_proto_goTypes = nil
	file_management_resource_v1alpha1_watch_proto_depIdxs = nil
}
