/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubevm.io/vink/pkg/k8s/apis/vink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualMachineClaims implements VirtualMachineClaimInterface
type FakeVirtualMachineClaims struct {
	Fake *FakeVinkV1alpha1
	ns   string
}

var virtualmachineclaimsResource = v1alpha1.SchemeGroupVersion.WithResource("virtualmachineclaims")

var virtualmachineclaimsKind = v1alpha1.SchemeGroupVersion.WithKind("VirtualMachineClaim")

// Get takes name of the virtualMachineClaim, and returns the corresponding virtualMachineClaim object, and an error if there is any.
func (c *FakeVirtualMachineClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineClaim, err error) {
	emptyResult := &v1alpha1.VirtualMachineClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(virtualmachineclaimsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineClaim), err
}

// List takes label and field selectors, and returns the list of VirtualMachineClaims that match those selectors.
func (c *FakeVirtualMachineClaims) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineClaimList, err error) {
	emptyResult := &v1alpha1.VirtualMachineClaimList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(virtualmachineclaimsResource, virtualmachineclaimsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualMachineClaimList{ListMeta: obj.(*v1alpha1.VirtualMachineClaimList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualMachineClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineClaims.
func (c *FakeVirtualMachineClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(virtualmachineclaimsResource, c.ns, opts))

}

// Create takes the representation of a virtualMachineClaim and creates it.  Returns the server's representation of the virtualMachineClaim, and an error, if there is any.
func (c *FakeVirtualMachineClaims) Create(ctx context.Context, virtualMachineClaim *v1alpha1.VirtualMachineClaim, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineClaim, err error) {
	emptyResult := &v1alpha1.VirtualMachineClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(virtualmachineclaimsResource, c.ns, virtualMachineClaim, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineClaim), err
}

// Update takes the representation of a virtualMachineClaim and updates it. Returns the server's representation of the virtualMachineClaim, and an error, if there is any.
func (c *FakeVirtualMachineClaims) Update(ctx context.Context, virtualMachineClaim *v1alpha1.VirtualMachineClaim, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineClaim, err error) {
	emptyResult := &v1alpha1.VirtualMachineClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(virtualmachineclaimsResource, c.ns, virtualMachineClaim, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineClaim), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualMachineClaims) UpdateStatus(ctx context.Context, virtualMachineClaim *v1alpha1.VirtualMachineClaim, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineClaim, err error) {
	emptyResult := &v1alpha1.VirtualMachineClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(virtualmachineclaimsResource, "status", c.ns, virtualMachineClaim, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineClaim), err
}

// Delete takes name of the virtualMachineClaim and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(virtualmachineclaimsResource, c.ns, name, opts), &v1alpha1.VirtualMachineClaim{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(virtualmachineclaimsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualMachineClaimList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineClaim.
func (c *FakeVirtualMachineClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineClaim, err error) {
	emptyResult := &v1alpha1.VirtualMachineClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(virtualmachineclaimsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineClaim), err
}
