/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubevm.io/vink/pkg/k8s/apis/vink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualMachineSummaries implements VirtualMachineSummaryInterface
type FakeVirtualMachineSummaries struct {
	Fake *FakeVinkV1alpha1
	ns   string
}

var virtualmachinesummariesResource = v1alpha1.SchemeGroupVersion.WithResource("virtualmachinesummaries")

var virtualmachinesummariesKind = v1alpha1.SchemeGroupVersion.WithKind("VirtualMachineSummary")

// Get takes name of the virtualMachineSummary, and returns the corresponding virtualMachineSummary object, and an error if there is any.
func (c *FakeVirtualMachineSummaries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineSummary, err error) {
	emptyResult := &v1alpha1.VirtualMachineSummary{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(virtualmachinesummariesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineSummary), err
}

// List takes label and field selectors, and returns the list of VirtualMachineSummaries that match those selectors.
func (c *FakeVirtualMachineSummaries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineSummaryList, err error) {
	emptyResult := &v1alpha1.VirtualMachineSummaryList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(virtualmachinesummariesResource, virtualmachinesummariesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualMachineSummaryList{ListMeta: obj.(*v1alpha1.VirtualMachineSummaryList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualMachineSummaryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineSummaries.
func (c *FakeVirtualMachineSummaries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(virtualmachinesummariesResource, c.ns, opts))

}

// Create takes the representation of a virtualMachineSummary and creates it.  Returns the server's representation of the virtualMachineSummary, and an error, if there is any.
func (c *FakeVirtualMachineSummaries) Create(ctx context.Context, virtualMachineSummary *v1alpha1.VirtualMachineSummary, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineSummary, err error) {
	emptyResult := &v1alpha1.VirtualMachineSummary{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(virtualmachinesummariesResource, c.ns, virtualMachineSummary, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineSummary), err
}

// Update takes the representation of a virtualMachineSummary and updates it. Returns the server's representation of the virtualMachineSummary, and an error, if there is any.
func (c *FakeVirtualMachineSummaries) Update(ctx context.Context, virtualMachineSummary *v1alpha1.VirtualMachineSummary, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineSummary, err error) {
	emptyResult := &v1alpha1.VirtualMachineSummary{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(virtualmachinesummariesResource, c.ns, virtualMachineSummary, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineSummary), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualMachineSummaries) UpdateStatus(ctx context.Context, virtualMachineSummary *v1alpha1.VirtualMachineSummary, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineSummary, err error) {
	emptyResult := &v1alpha1.VirtualMachineSummary{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(virtualmachinesummariesResource, "status", c.ns, virtualMachineSummary, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineSummary), err
}

// Delete takes name of the virtualMachineSummary and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineSummaries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(virtualmachinesummariesResource, c.ns, name, opts), &v1alpha1.VirtualMachineSummary{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineSummaries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(virtualmachinesummariesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualMachineSummaryList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineSummary.
func (c *FakeVirtualMachineSummaries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineSummary, err error) {
	emptyResult := &v1alpha1.VirtualMachineSummary{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(virtualmachinesummariesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineSummary), err
}
